apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
    minimum: 2.0
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
