apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
    - ExampleAdded
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
      maximum: 15.0 ## Puesto solo para probar el ejemplo
  storageClassName: slow
  selector:
    matchLabels:
      release: "stable"
    matchExpressions:
      - {key: environment, operator: In, values: [dev]}
    matchExpressions: ## Otra forma de hacerlo
    - key: environment
      operator: In
      values:
        - dev