apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
    minimum: 2.0 ## Agregado solo para probar la funcionalidad del array en el mapeo
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
