apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitor
  labels:
    app: prometheus
data:
  prometheus.yml: "global:\n  scrape_interval:     15s # Default is every 1 minute.\n\
    \  evaluation_interval: 15s # Default is every 1 minute.\n  # scrape_timeout is\
    \ set to the global default (10s).\nscrape_configs:\n  - job_name: 'services-metrics'\n\
    \    metrics_path: '/actuator/prometheus'\n    scrape_interval: 5s\n    static_configs:\n\
    \      - targets:\n        - auth-svc.service:80\n        - product-svc.service:80\n\
    \        - order-svc.service:80\n        - inventory-svc.service:80\n        -\
    \ gateway-svc.service:80\n        - admin-svc.service:80\n  - job_name: 'jaeger-metrics'\n\
    \    metrics_path: '/metrics'\n    scrape_interval: 5s\n    static_configs:\n\
    \      - targets:\n        - jaeger-agent:14271\n        - jaeger-collector:14269\n\
    \        - jaeger-query:16687\n  - job_name: 'database-metrics'\n    metrics_path:\
    \ '/metrics'\n    scrape_interval: 5s\n    static_configs:\n      - targets:\n\
    \        - elasticsearch:9114\n        - postgres.data:9187\n        - cassandra.data:7070\n\
    \        - rabbitmq.data:15692\n        - redis.data:9121 \nrule_files:\n  - rules.yml\n"
  rules.yml: "groups:\n- name: example\n  rules:\n\n  # Alert for any instance that\
    \ is unreachable for >5 minutes.\n  - alert: InstanceDown\n    expr: up == 0\n\
    \    for: 5s\n    labels:\n      severity: page\n    annotations:\n      summary:\
    \ \"Instance {{ $labels.instance }} down\"\n      description: \"{{ $labels.instance\
    \ }} of job {{ $labels.job }} has been down for more than 5 seconds.\"\n\n  #\
    \ Alert for any instance that has a median request latency >1s.\n  - alert: APIHighRequestLatency\n\
    \    expr: api_http_request_latencies_second{quantile=\"0.5\"} > 0.1\n    for:\
    \ 10m\n    annotations:\n      summary: \"High request latency on {{ $labels.instance\
    \ }}\"\n      description: \"{{ $labels.instance }} has a median request latency\
    \ above 1s (current value: {{ $value }}s)\"\n"
