kind: ConfigMap
apiVersion: v1
metadata:
  name: connect-metrics
  labels:
    app: my-cluster
data:
  connect-metrics.yaml: "# Inspired by kafka-connect rules\n# https://github.com/prometheus/jmx_exporter/blob/master/example_configs/kafka-connect.yml\n\
    # See https://github.com/prometheus/jmx_exporter for more info about JMX Prometheus\
    \ Exporter metrics\nlowercaseOutputName: true\nlowercaseOutputLabelNames: true\n\
    rules:\n#kafka.connect:type=app-info,client-id=\"{clientid}\"\n#kafka.consumer:type=app-info,client-id=\"\
    {clientid}\"\n#kafka.producer:type=app-info,client-id=\"{clientid}\"\n- pattern:\
    \ 'kafka.(.+)<type=app-info, client-id=(.+)><>start-time-ms'\n  name: kafka_$1_start_time_seconds\n\
    \  labels:\n    clientId: \"$2\"\n  help: \"Kafka $1 JMX metric start time seconds\"\
    \n  type: GAUGE\n  valueFactor: 0.001\n- pattern: 'kafka.(.+)<type=app-info, client-id=(.+)><>(commit-id|version):\
    \ (.+)'\n  name: kafka_$1_$3_info\n  value: 1\n  labels:\n    clientId: \"$2\"\
    \n    $3: \"$4\"\n  help: \"Kafka $1 JMX metric info version and commit-id\"\n\
    \  type: GAUGE\n\n#kafka.producer:type=producer-topic-metrics,client-id=\"{clientid}\"\
    ,topic=\"{topic}\"\", partition=\"{partition}\"\n#kafka.consumer:type=consumer-fetch-manager-metrics,client-id=\"\
    {clientid}\",topic=\"{topic}\"\", partition=\"{partition}\"\n- pattern: kafka.(.+)<type=(.+)-metrics,\
    \ client-id=(.+), topic=(.+), partition=(.+)><>(.+-total|compression-rate|.+-avg|.+-replica|.+-lag|.+-lead)\n\
    \  name: kafka_$2_$6\n  labels:\n    clientId: \"$3\"\n    topic: \"$4\"\n   \
    \ partition: \"$5\"\n  help: \"Kafka $1 JMX metric type $2\"\n  type: GAUGE\n\n\
    #kafka.producer:type=producer-topic-metrics,client-id=\"{clientid}\",topic=\"\
    {topic}\"\n#kafka.consumer:type=consumer-fetch-manager-metrics,client-id=\"{clientid}\"\
    ,topic=\"{topic}\"\", partition=\"{partition}\"\n- pattern: kafka.(.+)<type=(.+)-metrics,\
    \ client-id=(.+), topic=(.+)><>(.+-total|compression-rate|.+-avg)\n  name: kafka_$2_$5\n\
    \  labels:\n    clientId: \"$3\"\n    topic: \"$4\"\n  help: \"Kafka $1 JMX metric\
    \ type $2\"\n  type: GAUGE\n\n#kafka.connect:type=connect-node-metrics,client-id=\"\
    {clientid}\",node-id=\"{nodeid}\"\n#kafka.consumer:type=consumer-node-metrics,client-id=consumer-1,node-id=\"\
    {nodeid}\"\n- pattern: kafka.(.+)<type=(.+)-metrics, client-id=(.+), node-id=(.+)><>(.+-total|.+-avg)\n\
    \  name: kafka_$2_$5\n  labels:\n    clientId: \"$3\"\n    nodeId: \"$4\"\n  help:\
    \ \"Kafka $1 JMX metric type $2\"\n  type: UNTYPED\n\n#kafka.connect:type=kafka-metrics-count,client-id=\"\
    {clientid}\"\n#kafka.consumer:type=consumer-fetch-manager-metrics,client-id=\"\
    {clientid}\"\n#kafka.consumer:type=consumer-coordinator-metrics,client-id=\"{clientid}\"\
    \n#kafka.consumer:type=consumer-metrics,client-id=\"{clientid}\"\n- pattern: kafka.(.+)<type=(.+)-metrics,\
    \ client-id=(.*)><>(.+-total|.+-avg|.+-bytes|.+-count|.+-ratio|.+-age|.+-flight|.+-threads|.+-connectors|.+-tasks|.+-ago)\n\
    \  name: kafka_$2_$4\n  labels:\n    clientId: \"$3\"\n  help: \"Kafka $1 JMX\
    \ metric type $2\"\n  type: GAUGE\n\n#kafka.connect:type=connector-metrics,connector=\"\
    {connector}\"\n- pattern: 'kafka.(.+)<type=connector-metrics, connector=(.+)><>(connector-class|connector-type|connector-version|status):\
    \ (.+)'\n  name: kafka_connect_connector_$3\n  value: 1\n  labels:\n    connector:\
    \ \"$2\"\n    $3: \"$4\"\n  help: \"Kafka Connect $3 JMX metric type connector\"\
    \n  type: GAUGE\n\n#kafka.connect:type=connector-task-metrics,connector=\"{connector}\"\
    ,task=\"{task}<> status\"\n- pattern: 'kafka.connect<type=connector-task-metrics,\
    \ connector=(.+), task=(.+)><>status: ([a-z-]+)'\n  name: kafka_connect_connector_task_status\n\
    \  value: 1\n  labels:\n    connector: \"$1\"\n    task: \"$2\"\n    status: \"\
    $3\"\n  help: \"Kafka Connect JMX Connector task status\"\n  type: GAUGE\n\n#kafka.connect:type=task-error-metrics,connector=\"\
    {connector}\",task=\"{task}\"\n#kafka.connect:type=source-task-metrics,connector=\"\
    {connector}\",task=\"{task}\"\n#kafka.connect:type=sink-task-metrics,connector=\"\
    {connector}\",task=\"{task}\"\n#kafka.connect:type=connector-task-metrics,connector=\"\
    {connector}\",task=\"{task}\"\n- pattern: kafka.connect<type=(.+)-metrics, connector=(.+),\
    \ task=(.+)><>(.+-total|.+-count|.+-ms|.+-ratio|.+-avg|.+-failures|.+-requests|.+-timestamp|.+-logged|.+-errors|.+-retries|.+-skipped)\n\
    \  name: kafka_connect_$1_$4\n  labels:\n    connector: \"$2\"\n    task: \"$3\"\
    \n  help: \"Kafka Connect JMX metric type $1\"\n  type: GAUGE\n\n#kafka.connect:type=connector-metrics,connector=\"\
    {connector}\"\n#kafka.connect:type=connect-worker-metrics,connector=\"{connector}\"\
    \n- pattern: kafka.connect<type=connect-worker-metrics, connector=(.+)><>([a-z-]+)\n\
    \  name: kafka_connect_worker_$2\n  labels:\n    connector: \"$1\"\n  help: \"\
    Kafka Connect JMX metric $1\"\n  type: GAUGE\n\n#kafka.connect:type=connect-worker-metrics\n\
    - pattern: kafka.connect<type=connect-worker-metrics><>([a-z-]+)\n  name: kafka_connect_worker_$1\n\
    \  help: \"Kafka Connect JMX metric worker\"\n  type: GAUGE\n\n#kafka.connect:type=connect-worker-rebalance-metrics\n\
    - pattern: kafka.connect<type=connect-worker-rebalance-metrics><>([a-z-]+)\n \
    \ name: kafka_connect_worker_rebalance_$1\n  help: \"Kafka Connect JMX metric\
    \ rebalance information\"\n  type: GAUGE\n"
