apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: tiansh-monitoring
data:
  prometheus.yml: "global:\n  scrape_interval:     15s\n  evaluation_interval: 15s\n\
    scrape_configs:\n- job_name: \"kubernetes-apiservers\"\n  kubernetes_sd_configs:\n\
    \  - role: endpoints\n  scheme: https\n  tls_config:\n    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n\
    \  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token\n  relabel_configs:\n\
    \  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name,\
    \ __meta_kubernetes_endpoint_port_name]\n    action: keep\n    regex: default;kubernetes;https\n\
    - job_name: \"kubernetes-nodes\"\n  kubernetes_sd_configs:\n  - role: node\n \
    \ scheme: https\n  tls_config:\n    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n\
    \  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token\n  relabel_configs:\n\
    \  - action: labelmap\n    regex: __meta_kubernetes_node_label_(.+)\n  - target_label:\
    \ __address__\n    replacement: kubernetes.default.svc:443\n  - source_labels:\
    \ [__meta_kubernetes_node_name]\n    regex: (.+)\n    target_label: __metrics_path__\n\
    \    replacement: /api/v1/nodes/${1}/proxy/metrics\n- job_name: \"kubernetes-cadvisor\"\
    \n  kubernetes_sd_configs:\n  - role: node\n  scheme: https\n  tls_config:\n \
    \   ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n  bearer_token_file:\
    \ /var/run/secrets/kubernetes.io/serviceaccount/token\n  relabel_configs:\n  -\
    \ action: labelmap\n    regex: __meta_kubernetes_node_label_(.+)\n  - target_label:\
    \ __address__\n    replacement: kubernetes.default.svc:443\n  - source_labels:\
    \ [__meta_kubernetes_node_name]\n    regex: (.+)\n    target_label: __metrics_path__\n\
    \    replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor\n- job_name: \"kubernetes-service-endpoints\"\
    \n  kubernetes_sd_configs:\n  - role: endpoints\n  relabel_configs:\n  - source_labels:\
    \ [__meta_kubernetes_service_annotation_prometheus_io_scrape]\n    action: keep\n\
    \    regex: true\n  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]\n\
    \    action: replace\n    target_label: __scheme__\n    regex: (https?)\n  - source_labels:\
    \ [__meta_kubernetes_service_annotation_prometheus_io_path]\n    action: replace\n\
    \    target_label: __metrics_path__\n    regex: (.+)\n  - source_labels: [__address__,\
    \ __meta_kubernetes_service_annotation_prometheus_io_port]\n    action: replace\n\
    \    target_label: __address__\n    regex: ([^:]+)(?::\\d+)?;(\\d+)\n    replacement:\
    \ $1:$2\n  - action: labelmap\n    regex: __meta_kubernetes_service_label_(.+)\n\
    \  - source_labels: [__meta_kubernetes_namespace]\n    action: replace\n    target_label:\
    \ kubernetes_namespace\n  - source_labels: [__meta_kubernetes_service_name]\n\
    \    action: replace\n    target_label: kubernetes_name\n- job_name: \"kubernetes-services\"\
    \n  kubernetes_sd_configs:\n  - role: service\n  metrics_path: /probe\n  params:\n\
    \    module: [http_2xx]\n  relabel_configs:\n  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]\n\
    \    action: keep\n    regex: true\n  - source_labels: [__address__]\n    target_label:\
    \ __param_target\n  - target_label: __address__\n    replacement: blackbox-exporter.example.com:9115\n\
    \  - source_labels: [__param_target]\n    target_label: instance\n  - action:\
    \ labelmap\n    regex: __meta_kubernetes_service_label_(.+)\n  - source_labels:\
    \ [__meta_kubernetes_namespace]\n    target_label: kubernetes_namespace\n  - source_labels:\
    \ [__meta_kubernetes_service_name]\n    target_label: kubernetes_name\n- job_name:\
    \ \"kubernetes-ingresses\"\n  kubernetes_sd_configs:\n  - role: ingress\n  relabel_configs:\n\
    \  - source_labels: [__meta_kubernetes_ingress_annotation_prometheus_io_probe]\n\
    \    action: keep\n    regex: true\n  - source_labels: [__meta_kubernetes_ingress_scheme,__address__,__meta_kubernetes_ingress_path]\n\
    \    regex: (.+);(.+);(.+)\n    replacement: ${1}://${2}${3}\n    target_label:\
    \ __param_target\n  - target_label: __address__\n    replacement: blackbox-exporter.example.com:9115\n\
    \  - source_labels: [__param_target]\n    target_label: instance\n  - action:\
    \ labelmap\n    regex: __meta_kubernetes_ingress_label_(.+)\n  - source_labels:\
    \ [__meta_kubernetes_namespace]\n    target_label: kubernetes_namespace\n  - source_labels:\
    \ [__meta_kubernetes_ingress_name]\n    target_label: kubernetes_name\n- job_name:\
    \ \"kubernetes-pods\"\n  kubernetes_sd_configs:\n  - role: pod\n  relabel_configs:\n\
    \  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]\n\
    \    action: keep\n    regex: true\n  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]\n\
    \    action: replace\n    target_label: __metrics_path__\n    regex: (.+)\n  -\
    \ source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]\n\
    \    action: replace\n    regex: ([^:]+)(?::\\d+)?;(\\d+)\n    replacement: $1:$2\n\
    \    target_label: __address__\n  - action: labelmap\n    regex: __meta_kubernetes_pod_label_(.+)\n\
    \  - source_labels: [__meta_kubernetes_namespace]\n    action: replace\n    target_label:\
    \ kubernetes_namespace\n  - source_labels: [__meta_kubernetes_pod_name]\n    action:\
    \ replace\n    target_label: kubernetes_pod_name\n"
