apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cluster-autoscaler
  namespace: kube-system
data:
  autoscaler.json: "{\n  \"use-external-etcd\": false,\n  \"distribution\": \"microk8s\"\
    ,\n  \"plateform\": \"cloudstack\",\n  \"image-credential-provider-bin-dir\":\
    \ \"/usr/local/bin\",\n  \"image-credential-provider-config\": \"/etc/kubernetes/credential.yaml\"\
    ,\n  \"listen\": \"unix:/var/run/cluster-autoscaler/autoscaler.sock\",\n  \"secret\"\
    : \"cloudstack\",\n  \"minNode\": 0,\n  \"maxNode\": 9,\n  \"maxPods\": 110,\n\
    \  \"maxNode-per-cycle\": 2,\n  \"nodegroup\": \"cloudstack-dev-microk8s\",\n\
    \  \"node-name-prefix\": \"autoscaled\",\n  \"managed-name-prefix\": \"managed\"\
    ,\n  \"controlplane-name-prefix\": \"master\",\n  \"nodePrice\": 0,\n  \"podPrice\"\
    : 0,\n  \"use-etc-hosts\": true,\n  \"use-cloudinit-config\": false,\n  \"cloudinit-file-owner\"\
    : \"root:adm\",\n  \"cloudinit-file-mode\": 420,\n  \"allow-upgrade\": false,\n\
    \  \"optionals\": {\n    \"pricing\": false,\n    \"getAvailableMachineTypes\"\
    : false,\n    \"newNodeGroup\": false,\n    \"templateNodeInfo\": false,\n   \
    \ \"createNodeGroup\": false,\n    \"deleteNodeGroup\": false\n  },\n  \"microk8s\"\
    : {\n    \"address\": \"172.16.0.10:25000\",\n    \"token\": \"....\",\n    \"\
    use-nlb\": true,\n    \"nlb-addresses\": [\n      \"172.16.0.10\"\n    ],\n  \
    \  \"channel\": \"1.30/stable\"\n  },\n  \"default-machine\": \"medium\",\n  \"\
    cloud-init\": {\n    \"package_update\": false,\n    \"package_upgrade\": false,\n\
    \    \"growpart\": {\n      \"ignore_growroot_disabled\": false,\n      \"mode\"\
    : \"auto\",\n      \"devices\": [\n        \"/\"\n      ]\n    },\n    \"runcmd\"\
    : [\n      \"echo '172.16.0.10 cloudstack-dev-microk8s-masterkube cloudstack-dev-microk8s-masterkube.aldunelabs.com'\
    \ >> /etc/hosts\"\n    ]\n  },\n  \"ssh-infos\": {\n    \"wait-ssh-ready-seconds\"\
    : 180,\n    \"user\": \"kubernetes\",\n    \"ssh-private-key\": \"/etc/ssh/id_rsa\"\
    \n  },\n  \"autoscaling-options\": {\n    \"scaleDownUtilizationThreshold\": 0.5,\n\
    \    \"scaleDownGpuUtilizationThreshold\": 0.5,\n    \"scaleDownUnneededTime\"\
    : \"1m\",\n    \"scaleDownUnreadyTime\": \"1m\",\n    \"maxNodeProvisionTime\"\
    : \"15m\",\n    \"zeroOrMaxNodeScaling\": false,\n    \"ignoreDaemonSetsUtilization\"\
    : true\n  },\n  \"credential-provider-config\": {\n    \"apiVersion\": \"kubelet.config.k8s.io/v1\"\
    ,\n    \"kind\": \"CredentialProviderConfig\",\n    \"providers\": [\n      {\n\
    \        \"name\": \"ecr-credential-provider\",\n        \"matchImages\": [\n\
    \          \"*.dkr.ecr.*.amazonaws.com\",\n          \"*.dkr.ecr.*.amazonaws.cn\"\
    ,\n          \"*.dkr.ecr-fips.*.amazonaws.com\",\n          \"*.dkr.ecr.us-iso-east-1.c2s.ic.gov\"\
    ,\n          \"*.dkr.ecr.us-isob-east-1.sc2s.sgov.gov\"\n        ],\n        \"\
    defaultCacheDuration\": \"12h\",\n        \"apiVersion\": \"credentialprovider.kubelet.k8s.io/v1\"\
    ,\n        \"args\": [\n          \"get-credentials\"\n        ],\n        \"\
    env\": [\n          {\n            \"name\": \"AWS_ACCESS_KEY_ID\",\n        \
    \    \"value\": \"<TO FILL>\"\n          },\n          {\n            \"name\"\
    : \"AWS_SECRET_ACCESS_KEY\",\n            \"value\": \"<TO FILL>\"\n         \
    \ }\n        ]\n      }\n    ]\n  }\n}\n"
  grpc-config.json: "{\n  \"address\": \"unix:/var/run/cluster-autoscaler/autoscaler.sock\"\
    ,\n  \"secret\": \"cloudstack\",\n  \"timeout\": 300\n}"
  machines.json: "{\n    \"tiny\": {\n        \"memsize\": 2048,\n        \"vcpus\"\
    : 2,\n        \"cpuspeed\": 1000,\n        \"disksize\": 10240\n    },\n    \"\
    small\": {\n        \"memsize\": 4096,\n        \"vcpus\": 2,\n        \"cpuspeed\"\
    : 2000,\n        \"disksize\": 20480\n    },\n    \"medium\": {\n        \"memsize\"\
    : 4096,\n        \"vcpus\": 4,\n        \"cpuspeed\": 2000,\n        \"disksize\"\
    : 20480\n    },\n    \"large\": {\n        \"memsize\": 8192,\n        \"vcpus\"\
    : 4,\n        \"cpuspeed\": 2000,\n        \"disksize\": 51200\n    },\n    \"\
    xlarge\": {\n        \"memsize\": 16384,\n        \"vcpus\": 4,\n        \"cpuspeed\"\
    : 2000,\n        \"disksize\": 102400\n    },\n    \"2xlarge\": {\n        \"\
    memsize\": 16384,\n        \"vcpus\": 8,\n        \"cpuspeed\": 2000,\n      \
    \  \"disksize\": 102400\n    },\n    \"4xlarge\": {\n        \"memsize\": 32768,\n\
    \        \"vcpus\": 8,\n        \"cpuspeed\": 2000,\n        \"disksize\": 102400\n\
    \    }\n}"
  provider.json: "{\n  \"api-url\": \"http://192.168.4.21:8080/client/api\",\n  \"\
    api-key\": \"....\",\n  \"secret-key\": \"....\",\n  \"ssl-no-verify\": true,\n\
    \  \"ssh-key-name\": \"ssh-key\",\n  \"project-id\": \"f0b04e54-c61e-4311-bda2-c43743f31565\"\
    ,\n  \"zone-id\": \"4ad6c94f-a259-4dc2-b53b-06300150fe29\",\n  \"pod-id\": \"\
    1fb922b2-10df-492c-b298-42cfcecdb0c0\",\n  \"cluster-id\": \"c9a60b4f-f365-45b6-a82f-c1c435bd484b\"\
    ,\n  \"host-id\": \"41f20fa0-7f68-4b17-8f3b-938791894165\",\n  \"vpc-id\": \"\
    b312c377-9939-474b-af83-9aeb1309e391\",\n  \"hypervisor\": \"KVM\",\n  \"template\"\
    : \"899e5de0-fc10-491f-9f99-d034846554ed\",\n  \"timeout\": 300,\n  \"use-bind9\"\
    : false,\n  \"bind9-host\": \":53\",\n  \"rndc-key-file\": \"/etc/cluster/rndc.key\"\
    ,\n  \"network\": {\n    \"security-group\": {\n      \"control-plane\": \"\"\
    ,\n      \"worker-node\": \"\"\n    },\n    \"public-control-plane\": false,\n\
    \    \"public-worker-node\": false,\n    \"domain\": \"aldunelabs.ai\",\n    \"\
    interfaces\": [\n      {\n        \"enabled\": true,\n        \"primary\": true,\n\
    \        \"network\": \"vpc-01\",\n        \"dhcp\": true,\n        \"address\"\
    : \"172.16.0.13\",\n        \"netmask\": \"255.255.255.0\"\n      }\n    ]\n \
    \ }\n}\n"
