apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cluster-autoscaler
  namespace: kube-system
data:
  autoscaler.json: "{\n  \"use-external-etcd\": false,\n  \"distribution\": \"kubeadm\"\
    ,\n  \"plateform\": \"openstack\",\n  \"kubernetes-pki-srcdir\": \"/etc/kubernetes/pki\"\
    ,\n  \"kubernetes-pki-dstdir\": \"/etc/kubernetes/pki\",\n  \"image-credential-provider-bin-dir\"\
    : \"/usr/local/bin\",\n  \"image-credential-provider-config\": \"/etc/kubernetes/credential.yaml\"\
    ,\n  \"listen\": \"unix:/var/run/cluster-autoscaler/autoscaler.sock\",\n  \"secret\"\
    : \"openstack\",\n  \"minNode\": 0,\n  \"maxNode\": 9,\n  \"maxPods\": 110,\n\
    \  \"maxNode-per-cycle\": 2,\n  \"nodegroup\": \"openstack-dev-kubeadm\",\n  \"\
    node-name-prefix\": \"autoscaled\",\n  \"managed-name-prefix\": \"managed\",\n\
    \  \"controlplane-name-prefix\": \"master\",\n  \"nodePrice\": 0,\n  \"podPrice\"\
    : 0,\n  \"use-etc-hosts\": false,\n  \"use-cloudinit-config\": false,\n  \"cloudinit-file-owner\"\
    : \"root:adm\",\n  \"cloudinit-file-mode\": 420,\n  \"allow-upgrade\": false,\n\
    \  \"optionals\": {\n    \"pricing\": false,\n    \"getAvailableMachineTypes\"\
    : false,\n    \"newNodeGroup\": false,\n    \"templateNodeInfo\": false,\n   \
    \ \"createNodeGroup\": false,\n    \"deleteNodeGroup\": false\n  },\n  \"kubeadm\"\
    : {\n    \"address\": \"192.168.32.10:6443\",\n    \"token\": \"....\",\n    \"\
    ca\": \"sha256:....\",\n    \"extras-args\": [\n      \"--ignore-preflight-errors=All\"\
    \n    ]\n  },\n  \"default-machine\": \"medium\",\n  \"cloud-init\": {\n    \"\
    package_update\": false,\n    \"package_upgrade\": false,\n    \"growpart\": {\n\
    \      \"ignore_growroot_disabled\": false,\n      \"mode\": \"auto\",\n     \
    \ \"devices\": [\n        \"/\"\n      ]\n    },\n    \"runcmd\": [\n    ]\n \
    \ },\n  \"ssh-infos\": {\n    \"wait-ssh-ready-seconds\": 180,\n    \"user\":\
    \ \"kubernetes\",\n    \"ssh-private-key\": \"/etc/ssh/id_rsa\"\n  },\n  \"autoscaling-options\"\
    : {\n    \"scaleDownUtilizationThreshold\": 0.5,\n    \"scaleDownGpuUtilizationThreshold\"\
    : 0.5,\n    \"scaleDownUnneededTime\": \"1m\",\n    \"scaleDownUnreadyTime\":\
    \ \"1m\",\n    \"maxNodeProvisionTime\": \"15m\",\n    \"zeroOrMaxNodeScaling\"\
    : false,\n    \"ignoreDaemonSetsUtilization\": true\n  },\n  \"credential-provider-config\"\
    : {\n    \"apiVersion\": \"kubelet.config.k8s.io/v1\",\n    \"kind\": \"CredentialProviderConfig\"\
    ,\n    \"providers\": [\n      {\n        \"name\": \"ecr-credential-provider\"\
    ,\n        \"matchImages\": [\n          \"*.dkr.ecr.*.amazonaws.com\",\n    \
    \      \"*.dkr.ecr.*.amazonaws.cn\",\n          \"*.dkr.ecr-fips.*.amazonaws.com\"\
    ,\n          \"*.dkr.ecr.us-iso-east-1.c2s.ic.gov\",\n          \"*.dkr.ecr.us-isob-east-1.sc2s.sgov.gov\"\
    \n        ],\n        \"defaultCacheDuration\": \"12h\",\n        \"apiVersion\"\
    : \"credentialprovider.kubelet.k8s.io/v1\",\n        \"args\": [\n          \"\
    get-credentials\"\n        ],\n        \"env\": [\n          {\n            \"\
    name\": \"AWS_ACCESS_KEY_ID\",\n            \"value\": \"<TO FILL>\"\n       \
    \   },\n          {\n            \"name\": \"AWS_SECRET_ACCESS_KEY\",\n      \
    \      \"value\": \"<TO FILL>\"\n          }\n        ]\n      }\n    ]\n  }\n\
    }\n"
  grpc-config.yaml: 'address: unix:/var/run/cluster-autoscaler/autoscaler.sock

    '
  machines.json: "{\n    \"tiny\": {\n        \"memsize\": 2048,\n        \"vcpus\"\
    : 2,\n        \"disksize\": 10240\n    },\n    \"small\": {\n        \"memsize\"\
    : 4096,\n        \"vcpus\": 2,\n        \"disksize\": 20480\n    },\n    \"medium\"\
    : {\n        \"memsize\": 4096,\n        \"vcpus\": 4,\n        \"disksize\":\
    \ 20480\n    },\n    \"large\": {\n        \"memsize\": 8192,\n        \"vcpus\"\
    : 4,\n        \"disksize\": 51200\n    },\n    \"xlarge\": {\n        \"memsize\"\
    : 16384,\n        \"vcpus\": 4,\n        \"disksize\": 102400\n    },\n    \"\
    2xlarge\": {\n        \"memsize\": 16384,\n        \"vcpus\": 8,\n        \"disksize\"\
    : 102400\n    },\n    \"4xlarge\": {\n        \"memsize\": 32768,\n        \"\
    vcpus\": 8,\n        \"disksize\": 102400\n    }\n}"
  provider.json: "{\n  \"cloud\": \"openstack\",\n  \"image\": \"noble-kubernetes-flannel-v1.30.2-containerd-amd64\"\
    ,\n  \"region\": \"RegionOne\",\n  \"zone\": \"nova\",\n  \"keyName\": \"ssh-k8s-key\"\
    ,\n  \"timeout\": 300,\n  \"use-bind9\": false,\n  \"bind9-host\": \":53\",\n\
    \  \"rndc-key-file\": \"/etc/cluster/rndc.key\",\n  \"clouds\": {\n    \"openstack\"\
    : {\n      \"auth\": {\n        \"auth_url\": \"https://192.168.2.21/identity/v3/\"\
    ,\n        \"username\": \"username\",\n        \"password\": \"password\",\n\
    \        \"project_id\": \"123456789\",\n        \"project_name\": \"demo\",\n\
    \        \"user_domain_name\": \"Default\",\n        \"tenant_id\": \"\",\n  \
    \      \"tenant_name\": \"\",\n        \"domain_id\": \"\",\n        \"domain_name\"\
    : \"\",\n        \"application_credential_id\": \"\",\n        \"application_credential_name\"\
    : \"\",\n        \"application_credential_secret\": \"\",\n        \"system_scope\"\
    : \"\"\n      },\n      \"region_name\": \"RegionOne\",\n      \"interface\":\
    \ \"public\",\n      \"verify\": false,\n      \"identity_api_version\": 3\n \
    \   }\n  },\n  \"network\": {\n    \"security-group\": {\n      \"control-plane\"\
    : \"sg-k8s-external\",\n      \"worker-node\": \"sg-k8s-internal\"\n    },\n \
    \   \"floating-ip\": {\n      \"network\": \"public\",\n      \"control-plane\"\
    : false,\n      \"worker-node\": false\n    },\n    \"domain\": \"aldunelabs.ai\"\
    ,\n    \"interfaces\": [\n      {\n        \"enabled\": true,\n        \"primary\"\
    : true,\n        \"network\": \"private\",\n        \"dhcp\": true,\n        \"\
    address\": \"192.168.32.13\",\n        \"netmask\": \"255.255.255.0\"\n      }\n\
    \    ]\n  }\n}\n"
