apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cluster-autoscaler
  namespace: kube-system
data:
  autoscaler.json: "{\n  \"use-external-etcd\": false,\n  \"distribution\": \"microk8s\"\
    ,\n  \"plateform\": \"desktop\",\n  \"image-credential-provider-bin-dir\": \"\
    /usr/local/bin\",\n  \"image-credential-provider-config\": \"/etc/kubernetes/credential.yaml\"\
    ,\n  \"listen\": \"unix:/var/run/cluster-autoscaler/autoscaler.sock\",\n  \"secret\"\
    : \"desktop\",\n  \"minNode\": 0,\n  \"maxNode\": 9,\n  \"maxPods\": 110,\n  \"\
    maxNode-per-cycle\": 2,\n  \"nodegroup\": \"desktop-dev-microk8s\",\n  \"node-name-prefix\"\
    : \"autoscaled\",\n  \"managed-name-prefix\": \"managed\",\n  \"controlplane-name-prefix\"\
    : \"master\",\n  \"nodePrice\": 0,\n  \"podPrice\": 0,\n  \"use-etc-hosts\": false,\n\
    \  \"use-cloudinit-config\": false,\n  \"cloudinit-file-owner\": \"root:adm\"\
    ,\n  \"cloudinit-file-mode\": 420,\n  \"allow-upgrade\": false,\n  \"optionals\"\
    : {\n    \"pricing\": false,\n    \"getAvailableMachineTypes\": false,\n    \"\
    newNodeGroup\": false,\n    \"templateNodeInfo\": false,\n    \"createNodeGroup\"\
    : false,\n    \"deleteNodeGroup\": false\n  },\n  \"microk8s\": {\n    \"address\"\
    : \"172.16.92.70:25000\",\n    \"token\": \"....\",\n    \"use-nlb\": false,\n\
    \    \"nlb-addresses\": [\n      \"172.16.92.70\"\n    ],\n    \"channel\": \"\
    1.30/stable\",\n    \"extras-commands\": []\n  },\n  \"default-machine\": \"medium\"\
    ,\n  \"cloud-init\": {\n    \"package_update\": false,\n    \"package_upgrade\"\
    : false,\n    \"growpart\": {\n      \"ignore_growroot_disabled\": false,\n  \
    \    \"mode\": \"auto\",\n      \"devices\": [\n        \"/\"\n      ]\n    },\n\
    \    \"runcmd\": [\n    ]\n  },\n  \"ssh-infos\": {\n    \"wait-ssh-ready-seconds\"\
    : 180,\n    \"user\": \"kubernetes\",\n    \"ssh-private-key\": \"/etc/ssh/id_rsa\"\
    \n  },\n  \"autoscaling-options\": {\n    \"scaleDownUtilizationThreshold\": 0.5,\n\
    \    \"scaleDownGpuUtilizationThreshold\": 0.5,\n    \"scaleDownUnneededTime\"\
    : \"1m\",\n    \"scaleDownUnreadyTime\": \"1m\",\n    \"maxNodeProvisionTime\"\
    : \"15m\",\n    \"zeroOrMaxNodeScaling\": false,\n    \"ignoreDaemonSetsUtilization\"\
    : true\n  },\n  \"credential-provider-config\": {\n    \"apiVersion\": \"kubelet.config.k8s.io/v1\"\
    ,\n    \"kind\": \"CredentialProviderConfig\",\n    \"providers\": [\n      {\n\
    \        \"name\": \"ecr-credential-provider\",\n        \"matchImages\": [\n\
    \          \"*.dkr.ecr.*.amazonaws.com\",\n          \"*.dkr.ecr.*.amazonaws.cn\"\
    ,\n          \"*.dkr.ecr-fips.*.amazonaws.com\",\n          \"*.dkr.ecr.us-iso-east-1.c2s.ic.gov\"\
    ,\n          \"*.dkr.ecr.us-isob-east-1.sc2s.sgov.gov\"\n        ],\n        \"\
    defaultCacheDuration\": \"12h\",\n        \"apiVersion\": \"credentialprovider.kubelet.k8s.io/v1\"\
    ,\n        \"args\": [\n          \"get-credentials\"\n        ],\n        \"\
    env\": [\n          {\n            \"name\": \"AWS_ACCESS_KEY_ID\",\n        \
    \    \"value\": \"<TO FILL>\"\n          },\n          {\n            \"name\"\
    : \"AWS_SECRET_ACCESS_KEY\",\n            \"value\": \"<TO FILL>\"\n         \
    \ }\n        ]\n      }\n    ]\n  }\n}\n"
  grpc-config.yaml: 'address: unix:/var/run/cluster-autoscaler/autoscaler.sock

    '
  machines.json: "{\n    \"tiny\": {\n        \"memsize\": 2048,\n        \"vcpus\"\
    : 2,\n        \"disksize\": 10240\n    },\n    \"small\": {\n        \"memsize\"\
    : 4096,\n        \"vcpus\": 2,\n        \"disksize\": 20480\n    },\n    \"medium\"\
    : {\n        \"memsize\": 4096,\n        \"vcpus\": 4,\n        \"disksize\":\
    \ 20480\n    },\n    \"large\": {\n        \"memsize\": 8192,\n        \"vcpus\"\
    : 4,\n        \"disksize\": 51200\n    },\n    \"xlarge\": {\n        \"memsize\"\
    : 16384,\n        \"vcpus\": 4,\n        \"disksize\": 102400\n    },\n    \"\
    2xlarge\": {\n        \"memsize\": 16384,\n        \"vcpus\": 8,\n        \"disksize\"\
    : 102400\n    },\n    \"4xlarge\": {\n        \"memsize\": 32768,\n        \"\
    vcpus\": 8,\n        \"disksize\": 102400\n    }\n}\n"
  provider.json: "{\n  \"address\": \"10.0.0.21:5701\",\n  \"key\": \"/etc/ssl/certs/autoscaler-utility/client.key\"\
    ,\n  \"cert\": \"/etc/ssl/certs/autoscaler-utility/client.crt\",\n  \"cacert\"\
    : \"/etc/ssl/certs/autoscaler-utility/ca.crt\",\n  \"nodegroup\": \"desktop-dev-microk8s\"\
    ,\n  \"timeout\": 300,\n  \"template-name\": \"HBGK2QFPDI6GJHH722CN5Q9A7BVI1MQ6\"\
    ,\n  \"linked\": false,\n  \"autostart\": true,\n  \"region\": \"home\",\n  \"\
    zone\": \"office\",\n  \"use-bind9\": true,\n  \"bind9-host\": \"192.168.2.1:53\"\
    ,\n  \"rndc-key-file\": \"/etc/cluster/rndc.key\",\n  \"network\": {\n    \"domain\"\
    : \"aldunelabs.private\",\n    \"dns\": {\n      \"search\": [\n        \"aldunelabs.private\"\
    \n      ],\n      \"nameserver\": [\n        \"192.168.2.1\"\n      ]\n    },\n\
    \    \"interfaces\": [\n      {\n        \"enabled\": true,\n        \"primary\"\
    : true,\n        \"exists\": true,\n        \"network\": \"vmnet8\",\n       \
    \ \"type\": \"nat\",\n        \"adapter\": \"vmxnet3\",\n        \"mac-address\"\
    : \"generate\",\n        \"nic\": \"eth0\",\n        \"dhcp\": false,\n      \
    \  \"use-dhcp-routes\": false,\n        \"address\": \"172.16.92.73\",\n     \
    \   \"netmask\": \"255.255.255.0\",\n        \"routes\": [\n          {\n    \
    \        \"to\": \"default\",\n            \"via\": \"172.16.92.2\",\n       \
    \     \"metric\": 100\n          }\n        ]\n      },\n      {\n        \"enabled\"\
    : true,\n        \"primary\": false,\n        \"exists\": false,\n        \"network\"\
    : \"vmnet0\",\n        \"type\": \"bridged\",\n        \"adapter\": \"vmxnet3\"\
    ,\n        \"mac-address\": \"generate\",\n        \"nic\": \"eth1\",\n      \
    \  \"dhcp\": true,\n        \"use-dhcp-routes\": true,\n        \"routes\": [\n\
    \          {\n            \"to\": \"172.30.0.0/16\",\n            \"via\": \"\
    10.0.0.168\",\n            \"metric\": 100\n          }\n        ]\n      }\n\
    \    ]\n  }\n}\n"
  rndc.key: "key \"rndc-key\" {\n  algorithm hmac-sha256;\n  secret \"....\";\n};"
