kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: canal
  namespace: kube-system
  labels:
    k8s-app: canal
spec:
  selector:
    matchLabels:
      k8s-app: canal
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: canal
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      serviceAccountName: canal
      terminationGracePeriodSeconds: 0
      priorityClassName: system-node-critical
      initContainers:
      - name: install-cni
        image: docker.io/calico/cni:v3.24.1
        imagePullPolicy: IfNotPresent
        command:
        - /opt/cni/bin/install
        envFrom:
        - configMapRef:
            name: kubernetes-services-endpoint
            optional: true
        env:
        - name: CALICO_CNI_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: CNI_CONF_NAME
          value: 10-canal.conflist
        - name: CNI_NETWORK_CONFIG
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: cni_network_config
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CNI_MTU
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: veth_mtu
        - name: SLEEP
          value: 'false'
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          name: cni-bin-dir
        - mountPath: /host/etc/cni/net.d
          name: cni-net-dir
        securityContext:
          privileged: true
      - name: mount-bpffs
        image: docker.io/calico/node:v3.24.1
        imagePullPolicy: IfNotPresent
        command:
        - calico-node
        - -init
        - -best-effort
        volumeMounts:
        - mountPath: /sys/fs
          name: sys-fs
          mountPropagation: Bidirectional
        - mountPath: /var/run/calico
          name: var-run-calico
          mountPropagation: Bidirectional
        - mountPath: /nodeproc
          name: nodeproc
          readOnly: true
        securityContext:
          privileged: true
      containers:
      - name: calico-node
        image: docker.io/calico/node:v3.24.1
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: kubernetes-services-endpoint
            optional: true
        env:
        - name: DATASTORE_TYPE
          value: kubernetes
        - name: USE_POD_CIDR
          value: 'true'
        - name: WAIT_FOR_DATASTORE
          value: 'true'
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CALICO_CNI_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: CALICO_NETWORKING_BACKEND
          value: none
        - name: CLUSTER_TYPE
          value: k8s,canal
        - name: FELIX_IPTABLESREFRESHINTERVAL
          value: '60'
        - name: IP
          value: ''
        - name: CALICO_DISABLE_FILE_LOGGING
          value: 'true'
        - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
          value: ACCEPT
        - name: FELIX_IPV6SUPPORT
          value: 'false'
        - name: FELIX_HEALTHENABLED
          value: 'true'
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 25m
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/calico-node
              - -shutdown
        livenessProbe:
          exec:
            command:
            - /bin/calico-node
            - -felix-live
          periodSeconds: 10
          initialDelaySeconds: 10
          failureThreshold: 6
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 9099
            host: localhost
          periodSeconds: 10
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /host/etc/cni/net.d
          name: cni-net-dir
          readOnly: false
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /run/xtables.lock
          name: xtables-lock
          readOnly: false
        - mountPath: /var/run/calico
          name: var-run-calico
          readOnly: false
        - mountPath: /var/lib/calico
          name: var-lib-calico
          readOnly: false
        - name: policysync
          mountPath: /var/run/nodeagent
        - name: bpffs
          mountPath: /sys/fs/bpf
        - name: cni-log-dir
          mountPath: /var/log/calico/cni
          readOnly: true
      - name: kube-flannel
        image: quay.io/coreos/flannel:v0.15.1
        imagePullPolicy: IfNotPresent
        command:
        - /opt/bin/flanneld
        - --ip-masq
        - --kube-subnet-mgr
        securityContext:
          privileged: true
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: FLANNELD_IFACE
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: canal_iface
        - name: FLANNELD_IP_MASQ
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: masquerade
        volumeMounts:
        - mountPath: /run/xtables.lock
          name: xtables-lock
          readOnly: false
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: var-run-calico
        hostPath:
          path: /var/run/calico
      - name: var-lib-calico
        hostPath:
          path: /var/lib/calico
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
      - name: sys-fs
        hostPath:
          path: /sys/fs/
          type: DirectoryOrCreate
      - name: bpffs
        hostPath:
          path: /sys/fs/bpf
          type: Directory
      - name: nodeproc
        hostPath:
          path: /proc
      - name: flannel-cfg
        configMap:
          name: canal-config
      - name: cni-bin-dir
        hostPath:
          path: /opt/cni/bin
      - name: cni-net-dir
        hostPath:
          path: /etc/cni/net.d
      - name: cni-log-dir
        hostPath:
          path: /var/log/calico/cni
      - name: policysync
        hostPath:
          type: DirectoryOrCreate
          path: /var/run/nodeagent
