kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: canal-node
  namespace: kube-system
  labels:
    k8s-app: canal-node
spec:
  selector:
    matchLabels:
      k8s-app: canal-node
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: canal-node
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      serviceAccountName: canal-node
      terminationGracePeriodSeconds: 0
      priorityClassName: system-node-critical
      initContainers:
      - name: install-cni
        image: docker.io/calico/cni:v3.25.0
        imagePullPolicy: IfNotPresent
        command:
        - /opt/cni/bin/install
        envFrom:
        - configMapRef:
            name: kubernetes-services-endpoint
            optional: true
        env:
        - name: CALICO_CNI_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: CNI_CONF_NAME
          value: 10-canal.conflist
        - name: CNI_NETWORK_CONFIG
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: cni_network_config
        - name: ETCD_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: etcd_endpoints
        - name: ETCD_CA_CERT_FILE
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: etcd_ca
        - name: ETCD_KEY_FILE
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: etcd_key
        - name: ETCD_CERT_FILE
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: etcd_cert
        - name: CNI_MTU
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: veth_mtu
        - name: SLEEP
          value: 'false'
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          name: cni-bin-dir
        - mountPath: /host/etc/cni/net.d
          name: cni-net-dir
        - mountPath: /calico-secrets
          name: etcd-certs
        securityContext:
          privileged: true
      - name: mount-bpffs
        image: docker.io/calico/node:v3.25.0
        imagePullPolicy: IfNotPresent
        command:
        - calico-node
        - -init
        - -best-effort
        volumeMounts:
        - mountPath: /sys/fs
          name: sys-fs
          mountPropagation: Bidirectional
        - mountPath: /var/run/calico
          name: var-run-calico
          mountPropagation: Bidirectional
        - mountPath: /nodeproc
          name: nodeproc
          readOnly: true
        securityContext:
          privileged: true
      containers:
      - name: calico-node
        image: docker.io/calico/node:v3.25.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: kubernetes-services-endpoint
            optional: true
        env:
        - name: ETCD_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: etcd_endpoints
        - name: ETCD_CA_CERT_FILE
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: etcd_ca
        - name: ETCD_KEY_FILE
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: etcd_key
        - name: ETCD_CERT_FILE
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: etcd_cert
        - name: CALICO_K8S_NODE_REF
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CALICO_CNI_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: CALICO_NETWORKING_BACKEND
          value: none
        - name: CLUSTER_TYPE
          value: k8s,canal
        - name: FELIX_IPTABLESREFRESHINTERVAL
          value: '60'
        - name: IP
          value: ''
        - name: CALICO_DISABLE_FILE_LOGGING
          value: 'true'
        - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
          value: ACCEPT
        - name: FELIX_IPV6SUPPORT
          value: 'false'
        - name: FELIX_HEALTHENABLED
          value: 'true'
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 250m
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/calico-node
              - -shutdown
        livenessProbe:
          exec:
            command:
            - /bin/calico-node
            - -felix-live
          periodSeconds: 10
          initialDelaySeconds: 10
          failureThreshold: 6
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 9099
            host: localhost
          periodSeconds: 10
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /host/etc/cni/net.d
          name: cni-net-dir
          readOnly: false
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /run/xtables.lock
          name: xtables-lock
          readOnly: false
        - mountPath: /var/run/calico
          name: var-run-calico
          readOnly: false
        - mountPath: /var/lib/calico
          name: var-lib-calico
          readOnly: false
        - mountPath: /calico-secrets
          name: etcd-certs
        - name: policysync
          mountPath: /var/run/nodeagent
        - name: bpffs
          mountPath: /sys/fs/bpf
        - name: cni-log-dir
          mountPath: /var/log/calico/cni
          readOnly: true
      - name: flannel
        image: docker.io/flannelcni/flannel:v0.16.3
        imagePullPolicy: IfNotPresent
        env:
        - name: FLANNELD_ETCD_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: etcd_endpoints
        - name: ETCD_CA_CERT_FILE
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: etcd_ca
        - name: ETCD_KEY_FILE
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: etcd_key
        - name: ETCD_CERT_FILE
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: etcd_cert
        - name: FLANNELD_ETCD_CAFILE
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: etcd_ca
        - name: FLANNELD_ETCD_KEYFILE
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: etcd_key
        - name: FLANNELD_ETCD_CERTFILE
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: etcd_cert
        - name: FLANNELD_IFACE
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: canal_iface
        - name: FLANNELD_IP_MASQ
          valueFrom:
            configMapKeyRef:
              name: canal-config
              key: masquerade
        - name: FLANNELD_SUBNET_FILE
          value: /run/flannel/subnet.env
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/resolv.conf
          name: resolv
        - mountPath: /run/flannel
          name: run-flannel
        - mountPath: /calico-secrets
          name: etcd-certs
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: var-run-calico
        hostPath:
          path: /var/run/calico
      - name: var-lib-calico
        hostPath:
          path: /var/lib/calico
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
      - name: sys-fs
        hostPath:
          path: /sys/fs/
          type: DirectoryOrCreate
      - name: bpffs
        hostPath:
          path: /sys/fs/bpf
          type: Directory
      - name: nodeproc
        hostPath:
          path: /proc
      - name: run-flannel
        hostPath:
          path: /run/flannel
      - name: resolv
        hostPath:
          path: /etc/resolv.conf
      - name: cni-bin-dir
        hostPath:
          path: /opt/cni/bin
      - name: cni-net-dir
        hostPath:
          path: /etc/cni/net.d
      - name: cni-log-dir
        hostPath:
          path: /var/log/calico/cni
      - name: etcd-certs
        secret:
          secretName: calico-etcd-secrets
          defaultMode: 256
      - name: policysync
        hostPath:
          type: DirectoryOrCreate
          path: /var/run/nodeagent
