apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: productpage-api
  description: API for the reviews backend
spec:
  type: openapi
  lifecycle: production
  owner: frontend
  system: bookstageinfo
  definition: "swagger: \"2.0\"\ninfo:\n  description: \"This is the API of the Istio\
    \ BookInfo sample application.\"\n  version: \"1.0.0\"\n  title: \"BookInfo API\"\
    \n  termsOfService: \"https://istio.io/\"\n  license:\n    name: \"Apache 2.0\"\
    \n    url: \"http://www.apache.org/licenses/LICENSE-2.0.html\"\nbasePath: \"/api/v1\"\
    \ntags:\n- name: \"product\"\n  description: \"Information about a product (in\
    \ this case a book)\"\n- name: \"review\"\n  description: \"Review information\
    \ for a product\"\n- name: \"rating\"\n  description: \"Rating information for\
    \ a product\"\nexternalDocs:\n  description: \"Learn more about the Istio BookInfo\
    \ application\"\n  url: \"https://istio.io/docs/samples/bookinfo.html\"\npaths:\n\
    \  /products:\n    get:\n      tags:\n      - \"product\"\n      summary: \"List\
    \ all products\"\n      description: \"List all products available in the application\
    \ with a minimum amount of information.\"\n      operationId: \"getProducts\"\n\
    \      consumes:\n      - \"application/json\"\n      produces:\n      - \"application/json\"\
    \n      responses:\n        200:\n          description: \"successful operation\"\
    \n          schema:\n            type: \"array\"\n            items:\n       \
    \       $ref: \"#/definitions/Product\"\n  /products/{id}:\n    get:\n      tags:\n\
    \      - \"product\"\n      summary: \"Get individual product\"\n      description:\
    \ \"Get detailed information about an individual product with the given id.\"\n\
    \      operationId: \"getProduct\"\n      consumes:\n      - \"application/json\"\
    \n      produces:\n      - \"application/json\"\n      parameters:\n      - name:\
    \ \"id\"\n        in: \"path\"\n        description: \"Product id\"\n        required:\
    \ true\n        type: \"integer\"\n        format: \"int32\"\n      responses:\n\
    \        200:\n          description: \"successful operation\"\n          schema:\n\
    \            $ref: \"#/definitions/ProductDetails\"\n        400:\n          description:\
    \ \"Invalid product id\"\n  /products/{id}/reviews:\n    get:\n      tags:\n \
    \     - \"review\"\n      summary: \"Get reviews for a product\"\n      description:\
    \ \"Get reviews for a product, including review text and possibly ratings information.\"\
    \n      operationId: \"getProductReviews\"\n      consumes:\n      - \"application/json\"\
    \n      produces:\n      - \"application/json\"\n      parameters:\n      - name:\
    \ \"id\"\n        in: \"path\"\n        description: \"Product id\"\n        required:\
    \ true\n        type: \"integer\"\n        format: \"int32\"\n      responses:\n\
    \        200:\n          description: \"successful operation\"\n          schema:\n\
    \            $ref: \"#/definitions/ProductReviews\"\n        400:\n          description:\
    \ \"Invalid product id\"\n  /products/{id}/ratings:\n    get:\n      tags:\n \
    \     - \"rating\"\n      summary: \"Get ratings for a product\"\n      description:\
    \ \"Get ratings for a product, including stars and their color.\"\n      operationId:\
    \ \"getProductRatings\"\n      consumes:\n      - \"application/json\"\n     \
    \ produces:\n      - \"application/json\"\n      parameters:\n      - name: \"\
    id\"\n        in: \"path\"\n        description: \"Product id\"\n        required:\
    \ true\n        type: \"integer\"\n        format: \"int32\"\n      responses:\n\
    \        200:\n          description: \"successful operation\"\n          schema:\n\
    \            $ref: \"#/definitions/ProductRatings\"\n        400:\n          description:\
    \ \"Invalid product id\"\n\n\ndefinitions:\n  Product:\n    type: \"object\"\n\
    \    description: \"Basic information about a product\"\n    properties:\n   \
    \   id:\n        type: \"integer\"\n        format: \"int32\"\n        description:\
    \ \"Product id\"\n      title:\n        type: \"string\"\n        description:\
    \ \"Title of the book\"\n      descriptionHtml:\n        type: \"string\"\n  \
    \      description: \"Description of the book - may contain HTML tags\"\n    required:\n\
    \    - \"id\"\n    - \"title\"\n    - \"descriptionHtml\"\n  ProductDetails:\n\
    \    type: \"object\"\n    description: \"Detailed information about a product\"\
    \n    properties:\n      id:\n        type: \"integer\"\n        format: \"int32\"\
    \n        description: \"Product id\"\n      publisher:\n        type: \"string\"\
    \n        description: \"Publisher of the book\"\n      language:\n        type:\
    \ \"string\"\n        description: \"Language of the book\"\n      author:\n \
    \       type: \"string\"\n        description: \"Author of the book\"\n      ISBN-10:\n\
    \        type: \"string\"\n        description: \"ISBN-10 of the book\"\n    \
    \  ISBN-13:\n        type: \"string\"\n        description: \"ISBN-13 of the book\"\
    \n      year:\n        type: \"integer\"\n        format: \"int32\"\n        description:\
    \ \"Year the book was first published in\"\n      type:\n        type: \"string\"\
    \n        enum:\n          - \"paperback\"\n          - \"hardcover\"\n      \
    \  description: \"Type of the book\"\n      pages:\n        type: \"integer\"\n\
    \        format: \"int32\"\n        description: \"Number of pages of the book\"\
    \n    required:\n    - \"id\"\n    - \"publisher\"\n    - \"language\"\n    -\
    \ \"author\"\n    - \"ISBN-10\"\n    - \"ISBN-13\"\n    - \"year\"\n    - \"type\"\
    \n    - \"pages\"\n  ProductReviews:\n    type: \"object\"\n    description: \"\
    Object containing reviews for a product\"\n    properties:\n      id:\n      \
    \  type: \"integer\"\n        format: \"int32\"\n        description: \"Product\
    \ id\"\n      reviews:\n        type: \"array\"\n        description: \"List of\
    \ reviews\"\n        items:\n          $ref: \"#/definitions/Review\"\n    required:\n\
    \    - \"id\"\n    - \"reviews\"\n  Review:\n    type: \"object\"\n    description:\
    \ \"Review of a product\"\n    properties:\n      reviewer:\n        type: \"\
    string\"\n        description: \"Name of the reviewer\"\n      text:\n       \
    \ type: \"string\"\n        description: \"Review text\"\n      rating:\n    \
    \    $ref: \"#/definitions/Rating\"\n    required:\n    - \"reviewer\"\n    -\
    \ \"text\"\n  Rating:\n    type: \"object\"\n    description: \"Rating of a product\"\
    \n    properties:\n      stars:\n        type: \"integer\"\n        format: \"\
    int32\"\n        minimum: 1\n        maximum: 5\n        description: \"Number\
    \ of stars\"\n      color:\n        type: \"string\"\n        enum:\n        \
    \  - \"red\"\n          - \"black\"\n        description: \"Color in which stars\
    \ should be displayed\"\n    required:\n    - \"stars\"\n    - \"color\"\n  ProductRatings:\n\
    \    type: \"object\"\n    description: \"Object containing ratings of a product\"\
    \n    properties:\n      id:\n        type: \"integer\"\n        format: \"int32\"\
    \n        description: \"Product id\"\n      ratings:\n        type: \"object\"\
    \n        description: \"A hashmap where keys are reviewer names, values are number\
    \ of stars\"\n        additionalProperties: \n          type: \"string\"\n   \
    \ required:\n    - \"id\"\n    - \"ratings\""
