kind: ConfigMap
apiVersion: v1
metadata:
  name: fluent-bit-win-config
  namespace: logging
  labels:
    app.kubernetes.io/name: fluent-bit-win
    app.kubernetes.io/instance: fluent-bit-win
data:
  fluent-bit.conf: "[SERVICE]\n    # Flush\n    # =====\n    # set an interval of\
    \ seconds before to flush records to a destination\n    flush        1\n\n   \
    \ # Daemon\n    # ======\n    # instruct Fluent Bit to run in foreground or background\
    \ mode.\n    daemon       Off\n\n    # Log_Level\n    # =========\n    # Set the\
    \ verbosity level of the service, values can be:\n    #\n    # - error\n    #\
    \ - warning\n    # - info\n    # - debug\n    # - trace\n    #\n    # by default\
    \ 'info' is set, that means it includes 'error' and 'warning'.\n    log_level\
    \    debug\n\n    # Parsers File\n    # ============\n    # specify an optional\
    \ 'Parsers' configuration file\n    parsers_file parsers.conf\n\n    # Plugins\
    \ File\n    # ============\n    # specify an optional 'Plugins' configuration\
    \ file to load external plugins.\n    #plugins_file plugins.conf\n\n    # HTTP\
    \ Server\n    # ===========\n    # Enable/Disable the built-in HTTP Server for\
    \ metrics\n    http_server  Off\n    http_listen  0.0.0.0\n    http_port    2020\n\
    \n    # Storage\n    # =======\n    # Fluent Bit can use memory and filesystem\
    \ buffering based mechanisms\n    #\n    # - https://docs.fluentbit.io/manual/administration/buffering-and-storage\n\
    \    #\n    # storage metrics\n    # ---------------\n    # publish storage pipeline\
    \ metrics in '/api/v1/storage'. The metrics are\n    # exported only if the 'http_server'\
    \ option is enabled.\n    #\n    storage.metrics on\n\n    # storage.path\n  \
    \  # ------------\n    # absolute file system path to store filesystem data buffers\
    \ (chunks).\n    #\n    # storage.path /tmp/storage\n\n    # storage.sync\n  \
    \  # ------------\n    # configure the synchronization mode used to store the\
    \ data into the\n    # filesystem. It can take the values normal or full.\n  \
    \  #\n    # storage.sync normal\n\n    # storage.checksum\n    # ----------------\n\
    \    # enable the data integrity check when writing and reading data from the\n\
    \    # filesystem. The storage layer uses the CRC32 algorithm.\n    #\n    # storage.checksum\
    \ off\n\n    # storage.backlog.mem_limit\n    # -------------------------\n  \
    \  # if storage.path is set, Fluent Bit will look for data chunks that were\n\
    \    # not delivered and are still in the storage layer, these are called\n  \
    \  # backlog data. This option configure a hint of maximum value of memory\n \
    \   # to use when processing these records.\n    #\n    # storage.backlog.mem_limit\
    \ 5M\n\n[INPUT]\n    Name tail\n    Path C:\\\\var\\\\log\\\\containers\\\\*.log\n\
    \    Exclude_Path *fluent-bit*.log\n    Parser cri\n    Tag kube.*\n    Buffer_Chunk_Size\
    \ 10MB\n    Buffer_Max_Size 40MB\n    Mem_Buf_Limit 512MB\n    Refresh_Interval\
    \ 5\n\n[INPUT]\n    Name tail\n    Path C:\\\\var\\\\log\\\\bridge\\\\*.log\n\
    \    Tag bridge.*\n    Parser nssm1\n    Buffer_Chunk_Size 10MB\n    Buffer_Max_Size\
    \ 40MB\n    Mem_Buf_Limit 512MB\n    Refresh_Interval 5\n\n[INPUT]\n    Name tail\n\
    \    Path C:\\\\var\\\\log\\\\k2s.log\n    Tag centrallog.*\n    Parser centrallog\n\
    \    Buffer_Chunk_Size 10MB\n    Buffer_Max_Size 40MB\n    Mem_Buf_Limit 512MB\n\
    \    Refresh_Interval 5\n\n[INPUT]\n    Name tail\n    Path C:\\\\var\\\\log\\\
    \\cloud-init\\\\*.log\n    Tag cloudinit.*\n    Parser cloudinit\n    Buffer_Chunk_Size\
    \ 10MB\n    Buffer_Max_Size 40MB\n    Mem_Buf_Limit 512MB\n    Refresh_Interval\
    \ 5\n\n[INPUT]\n    Name tail\n    Path C:\\\\var\\\\log\\\\containerd\\\\*.log\n\
    \    Tag containerd.*\n    Parser nssm1\n    Buffer_Chunk_Size 10MB\n    Buffer_Max_Size\
    \ 40MB\n    Mem_Buf_Limit 512MB\n    Refresh_Interval 5\n\n[INPUT]\n    Name tail\n\
    \    Path C:\\\\var\\\\log\\\\dnsproxy\\\\*.log\n    Tag dnsproxy.*\n    Parser\
    \ dnsproxy\n    Buffer_Chunk_Size 10MB\n    Buffer_Max_Size 40MB\n    Mem_Buf_Limit\
    \ 512MB\n    Refresh_Interval 5\n\n[INPUT]\n    Name tail\n    Path C:\\\\var\\\
    \\log\\\\dockerd\\\\*.log\n    Tag dockerd.*\n    Parser nssm1\n    Buffer_Chunk_Size\
    \ 10MB\n    Buffer_Max_Size 40MB\n    Mem_Buf_Limit 512MB\n    Refresh_Interval\
    \ 5\n\n[INPUT]\n    Name tail\n    Path C:\\\\var\\\\log\\\\flanneld\\\\*.log\n\
    \    Tag flanneld.*\n    Parser nssm2\n    Buffer_Chunk_Size 10MB\n    Buffer_Max_Size\
    \ 40MB\n    Mem_Buf_Limit 512MB\n    Refresh_Interval 5\n\n[INPUT]\n    Name tail\n\
    \    Path C:\\\\var\\\\log\\\\httpproxy\\\\*.log\n    Tag httpproxy.*\n    Parser\
    \ nssm3\n    Buffer_Chunk_Size 10MB\n    Buffer_Max_Size 40MB\n    Mem_Buf_Limit\
    \ 512MB\n    Refresh_Interval 5\n\n[INPUT]\n    Name tail\n    Path C:\\\\var\\\
    \\log\\\\kubelet\\\\*.log\n    Tag kubelet.*\n    Parser nssm2\n    Buffer_Chunk_Size\
    \ 10MB\n    Buffer_Max_Size 40MB\n    Mem_Buf_Limit 512MB\n    Refresh_Interval\
    \ 5\n\n[INPUT]\n    Name tail\n    Path C:\\\\var\\\\log\\\\kubeproxy\\\\*.log\n\
    \    Tag kubeproxy.*\n    Parser kubeproxy\n    Buffer_Chunk_Size 10MB\n    Buffer_Max_Size\
    \ 40MB\n    Mem_Buf_Limit 512MB\n    Refresh_Interval 5\n\n[INPUT]\n    Name tail\n\
    \    Path C:\\\\var\\\\log\\\\vfprules\\\\*.log\n    Tag vfprules.*\n    Parser\
    \ nssm1\n    Buffer_Chunk_Size 10MB\n    Buffer_Max_Size 40MB\n    Mem_Buf_Limit\
    \ 512MB\n    Refresh_Interval 5\n\n[INPUT]\n    Name tail\n    Path C:\\\\var\\\
    \\log\\\\windows_exporter\\\\*.log\n    Tag windowsexporter.*\n    Parser nssm1\n\
    \    Buffer_Chunk_Size 10MB\n    Buffer_Max_Size 40MB\n    Mem_Buf_Limit 512MB\n\
    \    Refresh_Interval 5\n\n[FILTER]\n    Name kubernetes\n    Match kube.*\n \
    \   Kube_URL https://kubernetes.default.svc.cluster.local:443\n    Merge_Log On\n\
    \    K8S-Logging.Parser Off\n    K8S-Logging.Exclude Off\n    Buffer_Size 10MB\n\
    \n[FILTER]\n    Name nest\n    Match kube.*\n    Operation lift\n    Nested_under\
    \ kubernetes\n\n[FILTER]\n    Name modify\n    Match kube.*\n    Rename message\
    \ log\n    Rename pod_name k2s.pod.name\n    Rename namespace_name k2s.namespace.name\n\
    \    Rename host k2s.host.name\n    Remove container_image\n    Remove docker_id\n\
    \    Remove container_name\n    Remove pod_id\n    Remove annotations\n    Remove\
    \ labels\n    Remove time\n    Remove logtag\n    Remove container_hash\n\n[FILTER]\n\
    \    Name modify\n    Match bridge.*\n    Rename message log\n    Add k2s.host.name\
    \ ${COMPUTERNAME}\n    Add ident bridge\n\n[FILTER]\n    Name modify\n    Match\
    \ centrallog.*\n    Rename message log\n    Add k2s.host.name ${COMPUTERNAME}\n\
    \    Add ident k2s.exe\n\n[FILTER]\n    Name parser\n    Match centrallog.*\n\
    \    Parser cli\n    Reserve_Data true\n    Key_Name log\n\n[FILTER]\n    Name\
    \ modify\n    Match cloudinit.*\n    Rename message log\n    Add k2s.host.name\
    \ ${COMPUTERNAME}\n    Add ident cloud-init\n\n[FILTER]\n    Name modify\n   \
    \ Match containerd.*\n    Rename message log\n    Add k2s.host.name ${COMPUTERNAME}\n\
    \    Add ident containerd\n\n[FILTER]\n    Name modify\n    Match dnsproxy.*\n\
    \    Rename message log\n    Add k2s.host.name ${COMPUTERNAME}\n    Add ident\
    \ dnsproxy\n\n[FILTER]\n    Name modify\n    Match dockerd.*\n    Rename message\
    \ log\n    Add k2s.host.name ${COMPUTERNAME}\n    Add ident dockerd\n\n[FILTER]\n\
    \    Name modify\n    Match flanneld.*\n    Rename message log\n    Add k2s.host.name\
    \ ${COMPUTERNAME}\n    Add ident flanneld\n\n[FILTER]\n    Name modify\n    Match\
    \ httpproxy.*\n    Rename message log\n    Add k2s.host.name ${COMPUTERNAME}\n\
    \    Add ident httpproxy\n\n[FILTER]\n    Name modify\n    Match kubelet.*\n \
    \   Rename message log\n    Add k2s.host.name ${COMPUTERNAME}\n    Add ident kubelet\n\
    \n[FILTER]\n    Name modify\n    Match kubeproxy.*\n    Rename message log\n \
    \   Add k2s.host.name ${COMPUTERNAME}\n    Add ident kubeproxy\n    \n[FILTER]\n\
    \    Name modify\n    Match vfprules.*\n    Rename message log\n    Add k2s.host.name\
    \ ${COMPUTERNAME}\n    Add ident vfprules\n\n[FILTER]\n    Name modify\n    Match\
    \ windowsexporter.*\n    Rename message log\n    Add k2s.host.name ${COMPUTERNAME}\n\
    \    Add ident windowsexporter\n\n[FILTER]\n    Name     throttle\n    Match \
    \   *\n    Rate     800\n    Window   3\n    Print_Status  true\n    Interval\
    \ 30s\n\n[OUTPUT]\n    Name  opensearch\n    Match *\n    Host opensearch-cluster-master.logging.svc.cluster.local\n\
    \    Port 9200\n    Index k2s\n    Buffer_Size 10MB\n    Suppress_Type_Name On\n\
    \    Trace_Error       On\n    net.dns.resolver LEGACY #https://github.com/fluent/fluent-bit/issues/7105"
