apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: "[SERVICE]\n    Flush         1\n    Log_Level     info\n    Daemon\
    \        off\n    Parsers_File  parsers.conf\n    HTTP_Server   On\n    HTTP_Listen\
    \   0.0.0.0\n    HTTP_Port     2020\n\n@INCLUDE input-kubernetes.conf\n@INCLUDE\
    \ filter-kubernetes.conf\n@INCLUDE output-elasticsearch.conf\n"
  input-kubernetes.conf: "[INPUT]\n    Name              tail\n    Tag           \
    \    kube.*\n    Path              /var/log/containers/*.log\n    multiline.parser\
    \  docker, cri\n    DB                /var/log/flb_kube.db\n    Mem_Buf_Limit\
    \     5MB\n    Skip_Long_Lines   On\n    Refresh_Interval  10\n\n[INPUT]\n   \
    \ Name              systemd\n    Tag               host.*\n    Systemd_Filter\
    \    _SYSTEMD_UNIT=kubelet.service\n    Systemd_Filter    _SYSTEMD_UNIT=containerd.service\n\
    \    Systemd_Filter    _SYSTEMD_UNIT=docker.service\n"
  filter-kubernetes.conf: "[FILTER]\n    Name                kubernetes\n    Match\
    \               kube.*\n    Kube_URL            https://kubernetes.default.svc:443\n\
    \    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n\
    \    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token\n\
    \    Kube_Tag_Prefix     kube.var.log.containers.\n    Merge_Log           On\n\
    \    Merge_Log_Key       log_processed\n    K8S-Logging.Parser  On\n    K8S-Logging.Exclude\
    \ Off\n"
  output-elasticsearch.conf: "[OUTPUT]\n    Name            yc-logging\n    Match\
    \           kube.*\n    group_id        <\u0438\u0434\u0435\u043D\u0442\u0438\u0444\
    \u0438\u043A\u0430\u0442\u043E\u0440_\u043B\u043E\u0433-\u0433\u0440\u0443\u043F\
    \u043F\u044B>\n    resource_type   {kubernetes/namespace_name}\n    resource_id\
    \     {kubernetes/pod_name}\n    stream_name     {kubernetes/host}\n    message_key\
    \     log\n    level_key       severity\n    default_level   INFO\n    authorization\
    \   iam-key-file:/etc/secret/key.json\n\n[OUTPUT]\n    Name                  yc-logging\n\
    \    Match                 host.*\n    group_id              <\u0438\u0434\u0435\
    \u043D\u0442\u0438\u0444\u0438\u043A\u0430\u0442\u043E\u0440_\u043B\u043E\u0433\
    -\u0433\u0440\u0443\u043F\u043F\u044B>\n    resource_type         systemd\n  \
    \  resource_id           {_SYSTEMD_UNIT}\n    stream_name           {_HOSTNAME}\n\
    \    message_key           MESSAGE\n    level_key             SEVERITY\n    default_level\
    \         INFO\n    authorization         iam-key-file:/etc/secret/key.json\n"
  parsers.conf: "[PARSER]\n    Name   apache\n    Format regex\n    Regex  ^(?<host>[^\
    \ ]*) [^ ]* (?<user>[^ ]*) \\[(?<time>[^\\]]*)\\] \"(?<method>\\S+)(?: +(?<path>[^\\\
    \"]*?)(?: +\\S*)?)?\" (?<code>[^ ]*) (?<size>[^ ]*)(?: \"(?<referer>[^\\\"]*)\"\
    \ \"(?<agent>[^\\\"]*)\")?$\n    Time_Key time\n    Time_Format %d/%b/%Y:%H:%M:%S\
    \ %z\n\n[PARSER]\n    Name   apache2\n    Format regex\n    Regex  ^(?<host>[^\
    \ ]*) [^ ]* (?<user>[^ ]*) \\[(?<time>[^\\]]*)\\] \"(?<method>\\S+)(?: +(?<path>[^\
    \ ]*) +\\S*)?\" (?<code>[^ ]*) (?<size>[^ ]*)(?: \"(?<referer>[^\\\"]*)\" \"(?<agent>[^\\\
    \"]*)\")?$\n    Time_Key time\n    Time_Format %d/%b/%Y:%H:%M:%S %z\n\n[PARSER]\n\
    \    Name   apache_error\n    Format regex\n    Regex  ^\\[[^ ]* (?<time>[^\\\
    ]]*)\\] \\[(?<level>[^\\]]*)\\](?: \\[pid (?<pid>[^\\]]*)\\])?( \\[client (?<client>[^\\\
    ]]*)\\])? (?<message>.*)$\n\n[PARSER]\n    Name   nginx\n    Format regex\n  \
    \  Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \\[(?<time>[^\\]]*)\\\
    ] \"(?<method>\\S+)(?: +(?<path>[^\\\"]*?)(?: +\\S*)?)?\" (?<code>[^ ]*) (?<size>[^\
    \ ]*)(?: \"(?<referer>[^\\\"]*)\" \"(?<agent>[^\\\"]*)\")?$\n    Time_Key time\n\
    \    Time_Format %d/%b/%Y:%H:%M:%S %z\n\n[PARSER]\n    Name   json\n    Format\
    \ json\n    Time_Key time\n    Time_Format %d/%b/%Y:%H:%M:%S %z\n\n[PARSER]\n\
    \    Name        docker\n    Format      json\n    Time_Key    time\n    Time_Format\
    \ %Y-%m-%dT%H:%M:%S.%L\n    Time_Keep   On\n\n[PARSER]\n    # http://rubular.com/r/tjUt3Awgg4\n\
    \    Name cri\n    Format regex\n    Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr)\
    \ (?<logtag>[^ ]*) (?<message>.*)$\n    Time_Key    time\n    Time_Format %Y-%m-%dT%H:%M:%S.%L%z\n\
    \n[PARSER]\n    Name        syslog\n    Format      regex\n    Regex       ^\\\
    <(?<pri>[0-9]+)\\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\\\
    /\\.\\-]*)(?:\\[(?<pid>[0-9]+)\\])?(?:[^\\:]*\\:)? *(?<message>.*)$\n    Time_Key\
    \    time\n    Time_Format %b %d %H:%M:%S\n\n[PARSER]\n    Name        syslog-rfc5424\n\
    \    Format      regex\n    Regex       ^\\<(?<pri>[0-9]{1,5})\\>1 (?<time>[^\
    \ ]+) (?<host>[^ ]+) (?<ident>[^ ]+) (?<pid>[-0-9]+) (?<msgid>[^ ]+) (?<extradata>(\\\
    [(.*?)\\]|-)) (?<message>.+)$\n    Time_Key    time\n    Time_Format %Y-%m-%dT%H:%M:%S.%L%z\n\
    \    Time_Keep   On\n\n[PARSER]\n    Name        syslog-rfc3164-local\n    Format\
    \      regex\n    Regex       ^\\<(?<pri>[0-9]+)\\>(?<time>[^ ]* {1,2}[^ ]* [^\
    \ ]*) (?<ident>[a-zA-Z0-9_\\/\\.\\-]*)(?:\\[(?<pid>[0-9]+)\\])?(?:[^\\:]*\\:)?\
    \ *(?<message>.*)$\n    Time_Key    time\n    Time_Format %b %d %H:%M:%S\n   \
    \ Time_Keep   On\n\n[PARSER]\n    Name        syslog-rfc3164\n    Format     \
    \ regex\n    Regex       /^\\<(?<pri>[0-9]+)\\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*)\
    \ (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\\/\\.\\-]*)(?:\\[(?<pid>[0-9]+)\\])?(?:[^\\\
    :]*\\:)? *(?<message>.*)$/\n    Time_Key    time\n    Time_Format %b %d %H:%M:%S\n\
    \    Time_Keep   On\n"
