apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dovecot
  namespace: mailserver
spec:
  selector:
    matchLabels:
      app: dovecot
  serviceName: dovecot
  replicas: 3
  volumeClaimTemplates:
  - metadata:
      name: storage
      namespace: mailserver
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: nfs-storage
  template:
    metadata:
      labels:
        app: dovecot
    spec:
      initContainers:
      - name: lsync-config
        image: busybox
        env:
        - name: INST
          value: '3'
        - name: NS
          value: mailserver
        - name: SVC
          value: dovecot
        - name: CLUSTER
          value: svc.cluster.local
        command:
        - /bin/sh
        args:
        - -c
        - cp /modfiles/lsyncd.lua /modconf; cp /modfiles/config.sh /modconf; chmod
          +x /modconf/config.sh; echo $HOSTNAME | tee /modconf/hostname; name=$(sed
          "s/[^a-z-]//g" /modconf/hostname); num=$(sed "s/[^0-9]//g" /modconf/hostname);
          ./modconf/config.sh; rm /modconf/hostname;
        volumeMounts:
        - name: modconf
          mountPath: /modconf
        - name: updconf
          mountPath: /modfiles/config.sh
          subPath: config.sh
        - name: basicconfig
          mountPath: /modfiles/lsyncd.lua
          subPath: lsyncd.lua
          readOnly: true
      containers:
      - name: healthz
        image: k8s.gcr.io/exechealthz:1.0
        args:
        - -cmd=nslookup dovecot.mailserver.svc.cluster.local
        ports:
        - name: healthz
          containerPort: 8080
          protocol: TCP
      - name: lsync
        image: quay.io/realshadow/lsyncd
        imagePullPolicy: Always
        env:
        - name: INST
          value: '3'
        - name: KEYPATH
          value: /keys
        - name: NS
          value: mailserver
        - name: SVC
          value: dovecot
        - name: CLUSTER
          value: svc.cluster.local
        volumeMounts:
        - name: storage
          mountPath: /mail
        - name: modconf
          mountPath: /config/
        - name: keyex
          mountPath: /keys/
        - name: tz-edmonton
          mountPath: /etc/localtime
        ports:
        - name: ssh
          containerPort: 22
          protocol: TCP
      - name: dovecot
        image: quay.io/realshadow/dovecot:latest
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 143
          initialDelaySeconds: 60
          periodSeconds: 60
        livenessProbe:
          tcpSocket:
            port: 143
          initialDelaySeconds: 60
          periodSeconds: 60
        volumeMounts:
        - name: storage
          mountPath: /mail
        - name: dhpem
          mountPath: /mnt/dh2048.pem
          subPath: dh2048.pem
        - name: tls-secret
          mountPath: /certs/
          readOnly: true
        - name: tz-edmonton
          mountPath: /etc/localtime
        - name: dovecot-conf
          mountPath: /etc/dovecot/dovecot.conf
          subPath: dovecot.conf
        - name: dovecot-dict-auth-conf-ext
          mountPath: /etc/dovecot/dovecot-dict-auth.conf.ext
          subPath: dovecot-dict-auth.conf.ext
        - name: dovecot-dict-sql-conf-ext
          mountPath: /etc/dovecot/dovecot-dict-sql.conf.ext
          subPath: dovecot-dict-sql.conf.ext
        - name: dovecot-ldap-conf-ext
          mountPath: /etc/dovecot/dovecot-ldap.conf.ext
          subPath: dovecot-ldap.conf.ext
        - name: dovecot-oauth2-conf-ext
          mountPath: /etc/dovecot/dovecot-oauth2.conf.ext
          subPath: dovecot-oauth2.conf.ext
        - name: dovecot-openssl-cnf
          mountPath: /etc/dovecot/dovecot-openssl.cnf
          subPath: dovecot-openssl.cnf
        - name: dovecot-sql-conf-ext
          mountPath: /etc/dovecot/dovecot-sql.conf.ext
          subPath: dovecot-sql.conf.ext
        - name: 10-auth-conf
          mountPath: /etc/dovecot/conf.d/10-auth.conf
          subPath: 10-auth.conf
        - name: 10-director-conf
          mountPath: /etc/dovecot/conf.d/10-director.conf
          subPath: 10-director.conf
        - name: 10-logging-conf
          mountPath: /etc/dovecot/conf.d/10-logging.conf
          subPath: 10-logging.conf
        - name: 10-mail-conf
          mountPath: /etc/dovecot/conf.d/10-mail.conf
          subPath: 10-mail.conf
        - name: 10-master-conf
          mountPath: /etc/dovecot/conf.d/10-master.conf
          subPath: 10-master.conf
        - name: 10-metrics-conf
          mountPath: /etc/dovecot/conf.d/10-metrics.conf
          subPath: 10-metrics.conf
        - name: 10-ssl-conf
          mountPath: /etc/dovecot/conf.d/10-ssl.conf
          subPath: 10-ssl.conf
        - name: 15-lda-conf
          mountPath: /etc/dovecot/conf.d/15-lda.conf
          subPath: 15-lda.conf
        - name: 15-mailboxes-conf
          mountPath: /etc/dovecot/conf.d/15-mailboxes.conf
          subPath: 15-mailboxes.conf
        - name: 20-imap-conf
          mountPath: /etc/doveoct/conf.d/20-imap.conf
          subPath: 20-imap.conf
        - name: 20-lmtp-conf
          mountPath: /etc/dovecot/conf.d/20-lmtp.conf
          subPath: 20-lmtp.conf
        - name: 20-managesieve-conf
          mountPath: /etc/dovecot/conf.d/20-managesieve.conf
          subPath: 20-managesieve.conf
        - name: 20-pop3-conf
          mountPath: /etc/dovecot/conf.d/20-pop3.conf
          subPath: 20-pop3.conf
        - name: 20-submission-conf
          mountPath: /etc/dovecot/conf.d/20-submission.conf
          subPath: 20-submission.conf
        - name: 90-acl-conf
          mountPath: /etc/dovecot/conf.d/90-acl.conf
          subPath: 90-acl.conf
        - name: 90-plugin-conf
          mountPath: /etc/dovecot/conf.d/90-plugin.conf
          subPath: 90-plugin.conf
        - name: 90-quota-conf
          mountPath: /etc/dovecot/conf.d/90-quota.conf
          subPath: 90-quota.conf
        - name: 90-sieve-conf
          mountPath: /etc/dovecot/conf.d/90-sieve.conf
          subPath: 90-sieve.conf
        - name: 90-sieve-extprograms-conf
          mountPath: /etc/dovecot/conf.d/90-sieve-extprograms.conf
          subPath: 90-sieve-extprograms.conf
        - name: auth-dict-conf-ext
          mountPath: /etc/dovecot/conf.d/auth-dict.conf.ext
          subPath: auth-dict.conf.ext
        - name: auth-sql-conf-ext
          mountPath: /etc/dovecot/conf.d/auth-sql.conf.ext
          subPath: auth-sql.conf.ext
        ports:
        - name: pop3-unenc
          containerPort: 110
          protocol: TCP
        - name: pop3-enc
          containerPort: 995
          protocol: TCP
        - name: imap-unenc
          containerPort: 143
          protocol: TCP
        - name: imap-enc
          containerPort: 993
          protocol: TCP
        - name: lmtp
          containerPort: 24
          protocol: TCP
        - name: sasl-auth
          containerPort: 13050
          protocol: TCP
      volumes:
      - name: dhpem
        secret:
          secretName: dhparam
      - name: tls-secret
        secret:
          secretName: tls-secret
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      - name: tz-edmonton
        hostPath:
          path: /usr/share/zoneinfo/America/Edmonton
      - name: basicconfig
        configMap:
          name: basicconfig
      - name: updconf
        configMap:
          name: updconf
      - name: modconf
        emptyDir: {}
      - name: keyex
        persistentVolumeClaim:
          claimName: keyexchange
      - name: dovecot-conf
        configMap:
          name: dovecot-conf
      - name: dovecot-dict-auth-conf-ext
        configMap:
          name: dovecot-dict-auth-conf-ext
      - name: dovecot-dict-sql-conf-ext
        configMap:
          name: dovecot-dict-sql-conf-ext
      - name: dovecot-ldap-conf-ext
        configMap:
          name: dovecot-ldap-conf-ext
      - name: dovecot-oauth2-conf-ext
        configMap:
          name: dovecot-oauth2-conf-ext
      - name: dovecot-openssl-cnf
        configMap:
          name: dovecot-openssl-cnf
      - name: dovecot-sql-conf-ext
        configMap:
          name: dovecot-sql-conf-ext
      - name: 10-auth-conf
        configMap:
          name: 10-auth-conf
      - name: 10-director-conf
        configMap:
          name: 10-director-conf
      - name: 10-logging-conf
        configMap:
          name: 10-logging-conf
      - name: 10-mail-conf
        configMap:
          name: 10-mail-conf
      - name: 10-master-conf
        configMap:
          name: 10-master-conf
      - name: 10-metrics-conf
        configMap:
          name: 10-metrics-conf
      - name: 10-ssl-conf
        configMap:
          name: 10-ssl-conf
      - name: 15-lda-conf
        configMap:
          name: 15-lda-conf
      - name: 15-mailboxes-conf
        configMap:
          name: 15-mailboxes-conf
      - name: 20-imap-conf
        configMap:
          name: 20-imap-conf
      - name: 20-lmtp-conf
        configMap:
          name: 20-lmtp-conf
      - name: 20-managesieve-conf
        configMap:
          name: 20-managesieve-conf
      - name: 20-pop3-conf
        configMap:
          name: 20-pop3-conf
      - name: 20-submission-conf
        configMap:
          name: 20-submission-conf
      - name: 90-acl-conf
        configMap:
          name: 90-acl-conf
      - name: 90-plugin-conf
        configMap:
          name: 90-plugin-conf
      - name: 90-quota-conf
        configMap:
          name: 90-quota-conf
      - name: 90-sieve-conf
        configMap:
          name: 90-sieve-conf
      - name: 90-sieve-extprograms-conf
        configMap:
          name: 90-sieve-extprograms-conf
      - name: auth-dict-conf-ext
        configMap:
          name: auth-dict-conf-ext
      - name: auth-sql-conf-ext
        configMap:
          name: auth-sql-conf-ext
