apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    app: gitea
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea
  annotations:
    secret.reloader.stakater.com/reload: gitea-tls
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  selector:
    matchLabels:
      app.kubernetes.io/name: gitea
      app.kubernetes.io/instance: gitea
  template:
    metadata:
      labels:
        app: gitea
        app.kubernetes.io/name: gitea
        app.kubernetes.io/instance: gitea
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: init-directories
        image: gitea/gitea:1.23.4-rootless
        command:
        - /usr/sbin/init_directory_structure.sh
        env:
        - name: GITEA_APP_INI
          value: /data/gitea/conf/app.ini
        - name: GITEA_CUSTOM
          value: /data/gitea
        - name: GITEA_WORK_DIR
          value: /data
        - name: GITEA_TEMP
          value: /tmp/gitea
        volumeMounts:
        - name: init
          mountPath: /usr/sbin
        - name: temp
          mountPath: /tmp
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      - name: init-app-ini
        image: gitea/gitea:1.23.4-rootless
        command:
        - /usr/sbin/config_environment.sh
        env:
        - name: GITEA_APP_INI
          value: /data/gitea/conf/app.ini
        - name: GITEA_CUSTOM
          value: /data/gitea
        - name: GITEA_WORK_DIR
          value: /data
        - name: GITEA_TEMP
          value: /tmp/gitea
        envFrom:
        - secretRef:
            name: gitea-secret
        volumeMounts:
        - name: config
          mountPath: /usr/sbin
        - name: temp
          mountPath: /tmp
        - name: data
          mountPath: /data
        - name: inline-config-sources
          mountPath: /env-to-ini-mounts/inlines/
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      - name: configure-gitea
        image: gitea/gitea:1.23.4-rootless
        command:
        - /usr/sbin/configure_gitea.sh
        securityContext:
          runAsUser: 1000
        env:
        - name: GITEA_APP_INI
          value: /data/gitea/conf/app.ini
        - name: GITEA_CUSTOM
          value: /data/gitea
        - name: GITEA_WORK_DIR
          value: /data
        - name: GITEA_TEMP
          value: /tmp/gitea
        - name: HOME
          value: /data/gitea/git
        - name: GITEA_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              key: GITEA_ADMIN_USERNAME
              name: gitea-secret
        - name: GITEA_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: GITEA_ADMIN_PASSWORD
              name: gitea-secret
        - name: GITEA_ADMIN_PASSWORD_MODE
          value: keepUpdated
        volumeMounts:
        - name: init
          mountPath: /usr/sbin
        - name: temp
          mountPath: /tmp
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      terminationGracePeriodSeconds: 60
      containers:
      - name: gitea
        image: gitea/gitea:1.23.4-rootless
        env:
        - name: SSH_LISTEN_PORT
          value: '2222'
        - name: SSH_PORT
          value: '22'
        - name: GITEA_APP_INI
          value: /data/gitea/conf/app.ini
        - name: GITEA_CUSTOM
          value: /data/gitea
        - name: GITEA_WORK_DIR
          value: /data
        - name: GITEA_TEMP
          value: /tmp/gitea
        - name: TMPDIR
          value: /tmp/gitea
        - name: HOME
          value: /data/gitea/git
        ports:
        - name: ssh
          containerPort: 2222
        - name: http
          containerPort: 3000
        - name: redirect
          containerPort: 3080
        livenessProbe:
          failureThreshold: 10
          initialDelaySeconds: 200
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: redirect
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: redirect
          timeoutSeconds: 1
        volumeMounts:
        - name: temp
          mountPath: /tmp
        - name: data
          mountPath: /data
        - name: tls
          mountPath: /data/gitea/https
          readOnly: true
        resources: {}
      volumes:
      - name: tls
        secret:
          secretName: gitea-tls
          defaultMode: 420
      - name: init
        secret:
          secretName: gitea-init
          defaultMode: 110
      - name: config
        secret:
          secretName: gitea
          defaultMode: 110
      - name: inline-config-sources
        configMap:
          name: gitea-inline-config
      - name: temp
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: gitea-pvc
