apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-graphite-exporter-config
data:
  graphite_mapping.conf: "---\n# All FreeNAS metrics start with server.<server_name>\n\
    # https://www.truenas.com/community/threads/mapping-of-freenas-data-sent-to-graphite_exporter-part-of-prometheus.80948/\n\
    # https://blog.bradbeattie.com/freenas-to-prometheus/\n\n# Validate configuration\
    \ with:\n# /path/to/graphite_exporter --check-config --graphite.mapping-config=/path/to/this_file.yml\n\
    # graphite_exporter --check-config --graphite.mapping-config=files/configs/present/graphite_mapping-2.yml\n\
    \n# To develop mappings locally:\n# graphite_exporter --log.level=debug --graphite.mapping-config=\n\
    # nc localhost 9109 < graphite-sample.txt\n# curl localhost:9108/metrics -s |\
    \ grep ^freenas | less\n\n# Mapping syntax is based on statsd_exporter.\n# https://github.com/prometheus/statsd_exporter#regular-expression-matching\n\
    mappings:\n  - match: 'servers\\.([^_]*)_([^_]*)_([^_]*)_([^_]*)\\.disktemp-(.*)\\\
    .temperature'\n    match_type: regex\n    name: \"freenas_disk_temperature\"\n\
    \    labels:\n      instance: '${1}.${2}.${3}.${4}'\n      job: freenas-graphite\n\
    \      disk: '${5}'\n  - match: 'servers\\.([^_]*)_([^_]*)_([^_]*)_([^_]*)\\.cputemp-(.*)\\\
    .temperature'\n    match_type: regex\n    name: \"freenas_cpu_temperature\"\n\
    \    labels:\n      instance: '${1}.${2}.${3}.${4}'\n      job: freenas-graphite\n\
    \      cpu: '${5}'\n\n  # When \"Report CPU usage in percent\" is NOT selected.\
    \ (default)\n  - match: 'servers\\.([^_]*)_([^_]*)_([^_]*)_([^_]*)\\.aggregation_cpu_(.*)\\\
    .percent-(.*)'\n    match_type: regex\n    name: \"freenas_cpu_percent_${5}\"\n\
    \    labels:\n      instance: '${1}.${2}.${3}.${4}'\n      job: freenas-graphite\n\
    \      mode: '${6}'\n\n  # When \"Report CPU usage in percent\" is selected.\n\
    \  - match: 'servers\\.([^_]*)_([^_]*)_([^_]*)_([^_]*)\\.aggregation_cpu_(.*)\\\
    .cpu-(.*)'\n    match_type: regex\n    name: \"freenas_cpu_usage_${5}\"\n    labels:\n\
    \      instance: '${1}.${2}.${3}.${4}'\n      job: freenas-graphite\n      mode:\
    \ '${6}'\n\n  # When \"Report CPU usage in percent\" is NOT selected. (default)\n\
    \  - match: 'servers\\.([^_]*)_([^_]*)_([^_]*)_([^_]*)\\.cpu-(.*)\\.cpu-(.*)'\n\
    \    match_type: regex\n    name: \"freenas_cpu_usage\"\n    labels:\n      instance:\
    \ '${1}.${2}.${3}.${4}'\n      job: freenas-graphite\n      cpu: '${5}'\n    \
    \  mode: '${6}'\n\n  # When \"Report CPU usage in percent\" is selected.\n  -\
    \ match: 'servers\\.([^_]*)_([^_]*)_([^_]*)_([^_]*)\\.cpu-(.*)\\.percent-(.*)'\n\
    \    match_type: regex\n    name: \"freenas_cpu_percent\"\n    labels:\n     \
    \ instance: '${1}.${2}.${3}.${4}'\n      job: freenas-graphite\n      cpu: '${5}'\n\
    \      mode: '${6}'\n  - match: 'servers\\.([^_]*)_([^_]*)_([^_]*)_([^_]*)\\.df-(.*)\\\
    .df_complex-(.*)'\n    match_type: regex\n    name: 'freenas_df_${6}'\n    labels:\n\
    \      instance: '${1}.${2}.${3}.${4}'\n      job: freenas-graphite\n      filesystem:\
    \ '${5}'\n  - match: 'servers\\.([^_]*)_([^_]*)_([^_]*)_([^_]*)\\.disk-(.*)\\\
    .disk_(.*)\\.(.*)'\n    match_type: regex\n    name: 'freenas_disk_${6}_${7}'\n\
    \    labels:\n      instance: '${1}.${2}.${3}.${4}'\n      job: freenas-graphite\n\
    \      device: '${5}'\n  - match: 'servers\\.([^_]*)_([^_]*)_([^_]*)_([^_]*)\\\
    .interface-(.*)\\.if_(.*)\\.(.*)'\n    match_type: regex\n    name: 'freenas_interface_${7}_${6}'\n\
    \    labels:\n      instance: '${1}.${2}.${3}.${4}'\n      job: freenas-graphite\n\
    \      interface: '${5}'\n  - match: 'servers\\.([^_]*)_([^_]*)_([^_]*)_([^_]*)\\\
    .load\\.load\\.longterm'\n    match_type: regex\n    name: 'freenas_load_15'\n\
    \    labels:\n      instance: '${1}.${2}.${3}.${4}'\n      job: freenas-graphite\n\
    \  - match: 'servers\\.([^_]*)_([^_]*)_([^_]*)_([^_]*)\\.load\\.load\\.midterm'\n\
    \    match_type: regex\n    name: 'freenas_load_5'\n    labels:\n      instance:\
    \ '${1}.${2}.${3}.${4}'\n      job: freenas-graphite\n  - match: 'servers\\.([^_]*)_([^_]*)_([^_]*)_([^_]*)\\\
    .load\\.load\\.shortterm'\n    match_type: regex\n    name: 'freenas_load_1'\n\
    \    labels:\n      instance: '${1}.${2}.${3}.${4}'\n      job: freenas-graphite\n\
    \  - match: 'servers\\.([^_]*)_([^_]*)_([^_]*)_([^_]*)\\.memory\\.memory-(.*)'\n\
    \    match_type: regex\n    name: 'freenas_memory_${5}'\n    labels:\n      instance:\
    \ '${1}.${2}.${3}.${4}'\n      job: freenas-graphite\n  - match: 'servers\\.([^_]*)_([^_]*)_([^_]*)_([^_]*)\\\
    .swap\\.swap-(.*)'\n    match_type: regex\n    name: 'freenas_swap_${5}'\n   \
    \ labels:\n      instance: '${1}.${2}.${3}.${4}'\n      job: freenas-graphite\n\
    \  - match: 'servers\\.([^_]*)_([^_]*)_([^_]*)_([^_]*)\\.uptime\\.uptime'\n  \
    \  match_type: regex\n    name: freenas_uptime\n    labels:\n      job: freenas-graphite\n\
    \      instance: \"${1}.${2}.${3}.${4}\"\n  - match: 'servers\\.([^_]*)_([^_]*)_([^_]*)_([^_]*)\\\
    .processes\\.ps_state-(.*)'\n    match_type: regex\n    name: freenas_processes\n\
    \    labels:\n      job: freenas-graphite\n      instance: \"${1}.${2}.${3}.${4}\"\
    \n      state: \"${5}\"\n  - match: 'servers\\.([^_]*)_([^_]*)_([^_]*)_([^_]*)\\\
    .([^.]*)\\.([^.]*)$'\n    match_type: regex\n    name: freenas_graphite_${5}\n\
    \    labels:\n      job: freenas-graphite-raw\n      instance: \"${1}.${2}.${3}.${4}\"\
    \n      item: \"${6}\"\n  - match: 'servers\\.([^_]*)_([^_]*)_([^_]*)_([^_]*)\\\
    .(.*)'\n    match_type: regex\n    name: freenas_graphite_raw\n    labels:\n \
    \     job: freenas-graphite-raw\n      instance: \"${1}.${2}.${3}.${4}\"\n   \
    \   graphite_metric: \"${5}\"\n  - match: 'sensor.*.*'\n    name: sensor_${5}\n\
    \    labels:\n      job: esp32-sensors\n      instance: ${1}.${2}.${3}.${4}\n"
