apiVersion: apps/v1
kind: Deployment
metadata:
  name: ospd-openvas
  namespace: gvm
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: unconfined
    container.apparmor.security.beta.kubernetes.io/ospd-openvas: unconfined
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ospd-openvas
  template:
    metadata:
      labels:
        app: ospd-openvas
    spec:
      nodeSelector:
        type: edge
      initContainers:
      - name: gpg-data
        image: greenbone/gpg-data
        imagePullPolicy: Always
        volumeMounts:
        - name: gpg-data-mount
          mountPath: /mnt
        resources:
          requests:
            memory: 256Mi
            cpu: 200m
          limits:
            memory: 512Mi
            cpu: '1'
      - name: greenbone-feed-sync
        image: greenbone/greenbone-feed-sync
        command:
        - sh
        - -c
        args:
        - "set -e # Exit immediately if a command exits with a non-zero status.\n\n\
          touch /var/lib/openvas/feed-update.lock\nchown -R 1001:1001 /var/lib/openvas\n\
          chown -R 1001:1001 /var/lib/notus\n\n# NASL data sync\necho \"Starting nasl\
          \ sync...\"\nif ! greenbone-feed-sync --type nasl -vv; then\n  echo \"NASL\
          \ data sync failed, exiting...\"\n  exit 1\nfi\n\n# Notus data sync\necho\
          \ \"Starting notus sync...\"\nif ! greenbone-feed-sync --type notus -vv;\
          \ then\n  echo \"Notus data sync failed, exiting...\"\n  exit 1\nfi\n"
        volumeMounts:
        - name: vt-data-mount-ospd
          mountPath: /var/lib/openvas/plugins
        - name: notus-data-mount
          mountPath: /var/lib/notus
      containers:
      - name: ospd-openvas
        image: greenbone/ospd-openvas@sha256:b477792a75f2a5b50136f777cf5918c1921eaf72bc43672a5bc719019cb73338
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        command:
        - ospd-openvas
        - -f
        - --config
        - /etc/gvm/ospd-openvas.conf
        - --mqtt-broker-address
        - mqtt-broker.gvm.svc.cluster.local
        - --mqtt-broker-port
        - '1883'
        - --notus-feed-dir
        - /var/lib/notus/advisories
        - -m
        - '666'
        volumeMounts:
        - name: gpg-data-mount
          mountPath: /etc/openvas/gnupg
        - name: vt-data-mount-ospd
          mountPath: /var/lib/openvas/plugins
        - name: notus-data-mount
          mountPath: /var/lib/notus
        - name: ospd-openvas-socket-mount
          mountPath: /run/ospd
        - name: redis-socket-mount
          mountPath: /run/redis/
        - name: ospd-openvas-config-volume
          mountPath: /etc/gvm/
        resources:
          requests:
            memory: 2Gi
            cpu: '1'
          limits:
            memory: 2Gi
            cpu: '3'
      - name: ospd-socat-server
        image: alpine/socat@sha256:149edf25b072477b8c94ecc6120c4ed39159baf7f1ffd086f4db3a7523f82e65
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9390
        command:
        - socat
        - -d
        - -d
        - TCP-LISTEN:9390,reuseaddr,fork
        - UNIX-CONNECT:/run/ospd/ospd-openvas.sock
        volumeMounts:
        - name: ospd-openvas-socket-mount
          mountPath: /run/ospd
        resources:
          requests:
            memory: 16Mi
            cpu: 100m
          limits:
            memory: 64Mi
            cpu: 500m
      - name: redis-server
        image: greenbone/redis-server@sha256:d80fe73ac2d4c256f095e9da9f9480b4e7b1aff43d2360650f1f59676a02b3f7
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: redis-socket-mount
          mountPath: /run/redis/
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 1Gi
            cpu: '1'
      - name: notus-scanner
        image: greenbone/notus-scanner@sha256:b29cc50e42a3a323ba92574f7b12d3831d967272e01f877811f010b521a68ac4
        imagePullPolicy: IfNotPresent
        command:
        - /usr/local/bin/entrypoint
        args:
        - notus-scanner
        - -f
        volumeMounts:
        - name: notus-data-mount
          mountPath: /var/lib/notus
        - name: gpg-data-mount
          mountPath: /etc/openvas/gnupg
        env:
        - name: NOTUS_SCANNER_MQTT_BROKER_ADDRESS
          value: mqtt-broker.gvm.svc.cluster.local
        - name: NOTUS_SCANNER_MQTT_BROKER_PORT
          value: '1883'
        - name: NOTUS_SCANNER_PRODUCTS_DIRECTORY
          value: /var/lib/notus/products
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
          limits:
            memory: 256Mi
            cpu: 500m
      volumes:
      - name: vt-data-mount-ospd
        persistentVolumeClaim:
          claimName: vt-data-vol-ospd
      - name: notus-data-mount
        persistentVolumeClaim:
          claimName: notus-data-vol
      - name: gpg-data-mount
        emptyDir: {}
      - name: ospd-openvas-socket-mount
        emptyDir: {}
      - name: redis-socket-mount
        emptyDir: {}
      - name: ospd-openvas-config-volume
        configMap:
          name: ospd-openvas-config
