apiVersion: apps/v1
kind: Deployment
metadata:
  name: gvmd
  namespace: gvm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gvmd
  template:
    metadata:
      labels:
        app: gvmd
    spec:
      initContainers:
      - name: init-gvmd
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        args:
        - 'mkdir -p /var/lib/gvm/gvmd;

          chown 1001:1001 /var/lib/gvm/gvmd;

          chown 1001:1001 /var/lib/gvm;

          chmod 755 /var/lib/gvm;

          chown 1001:1001 /var/lib/gvm/data-objects;

          chmod 777 /var/lib/gvm/data-objects;

          '
        volumeMounts:
        - name: gvmd-data-mount
          mountPath: /var/lib/gvm
        - name: data-objects-mount
          mountPath: /var/lib/gvm/data-objects/gvmd
      - name: greenbone-feed-sync
        image: greenbone/greenbone-feed-sync
        command:
        - sh
        - -c
        args:
        - "set -e # Exit immediately if a command exits with a non-zero status.\n\n\
          # chown commands\nchown 1001:1001 /var/lib/gvm/scap-data\nchown 1001:1001\
          \ /var/lib/gvm/cert-data\n\n# SCAP data sync\necho \"Starting scap sync...\"\
          \nif ! greenbone-feed-sync --type scap -vv; then\n  echo \"SCAP data sync\
          \ failed, exiting...\"\n  exit 1\nfi\n\n# CERT data sync\necho \"Starting\
          \ cert sync...\"\nif ! greenbone-feed-sync --type cert; then\n  echo \"\
          CERT data sync failed, exiting...\"\n  exit 1\nfi\n\n# gvmd-data sync\n\
          echo \"Starting gvmd-data sync...\"\nif ! greenbone-feed-sync --type gvmd-data\
          \ -vv; then\n  echo \"gvmd-data sync failed, exiting...\"\n  exit 1\nfi\n\
          \n# report-formats sync\necho \"Starting report-formats sync...\"\nif !\
          \ greenbone-feed-sync --type report-formats -vv; then\n  echo \"gvmd-data\
          \ sync failed, exiting...\"\n  exit 1\nfi\n"
        volumeMounts:
        - name: gvmd-data-mount
          mountPath: /var/lib/gvm
        - name: scap-data-mount
          mountPath: /var/lib/gvm/scap-data/
        - name: cert-data-mount
          mountPath: /var/lib/gvm/cert-data
        - name: data-objects-mount
          mountPath: /var/lib/gvm/data-objects/gvmd
      containers:
      - name: gvmd
        image: greenbone/gvmd@sha256:9196a06a6edda011f337892975654bf86a1638016bc95f5d29deaf0c1e3c392b
        imagePullPolicy: IfNotPresent
        command:
        - /usr/local/bin/entrypoint
        args:
        - /mnt/gvmd-script/start-gvmd
        volumeMounts:
        - name: gvmd-data-mount
          mountPath: /var/lib/gvm
        - name: scap-data-mount
          mountPath: /var/lib/gvm/scap-data/
        - name: cert-data-mount
          mountPath: /var/lib/gvm/cert-data
        - name: data-objects-mount
          mountPath: /var/lib/gvm/data-objects/gvmd
        - name: gvmd-socket-mount
          mountPath: /run/gvmd
        - name: ospd-openvas-socket-mount
          mountPath: /run/ospd
        - name: psql-socket-mount
          mountPath: /var/run/postgresql
        - name: psql-data-mount
          mountPath: /var/lib/postgresql
        - name: start-gvmd-script-volume
          mountPath: /mnt/gvmd-script
        - name: gvmd-logging-conf-volume
          mountPath: /etc/gvm/
        resources:
          requests:
            memory: 2Gi
            cpu: 500m
          limits:
            memory: 4Gi
            cpu: '2'
      - name: gsa
        image: greenbone/gsa@sha256:9248a3688a81433502a609cf15bf01ed6cedff5ed7e9dd9d8d71e270a184ec23
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /login
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: gvmd-socket-mount
          mountPath: /run/gvmd
        resources:
          requests:
            memory: 128Mi
            cpu: 200m
            ephemeral-storage: 5Gi
          limits:
            memory: 256Mi
            cpu: 500m
            ephemeral-storage: 10Gi
      volumes:
      - name: gvmd-data-mount
        persistentVolumeClaim:
          claimName: gvmd-data-vol
      - name: scap-data-mount
        persistentVolumeClaim:
          claimName: scap-data-vol
      - name: cert-data-mount
        persistentVolumeClaim:
          claimName: cert-data-vol
      - name: data-objects-mount
        persistentVolumeClaim:
          claimName: data-objects-vol
      - name: psql-data-mount
        persistentVolumeClaim:
          claimName: psql-data-mount-pg-gvm-0
      - name: psql-socket-mount
        persistentVolumeClaim:
          claimName: psql-socket-mount-pg-gvm-0
      - name: gvmd-socket-mount
        persistentVolumeClaim:
          claimName: gvmd-socket-vol
      - name: ospd-openvas-socket-mount
        persistentVolumeClaim:
          claimName: ospd-openvas-socket-vol
      - name: start-gvmd-script-volume
        configMap:
          name: start-gvmd-script
          defaultMode: 493
      - name: gvmd-logging-conf-volume
        configMap:
          name: gvmd-logging-conf
