apiVersion: v1
data:
  harvester-csi-deployment.yaml: "apiVersion: apps/v1\nkind: DaemonSet\nmetadata:\n\
    \  name: harvester-csi-plugin\n  namespace: kube-system\nspec:\n  selector:\n\
    \    matchLabels:\n      app: harvester-csi-plugin\n  template:\n    metadata:\n\
    \      labels:\n        app: harvester-csi-plugin\n    spec:\n      containers:\n\
    \        - args:\n            - --v=5\n            - --csi-address=$(ADDRESS)\n\
    \            - --kubelet-registration-path=/var/lib/kubelet/harvester-plugins/driver.harvesterhci.io/csi.sock\n\
    \          env:\n            - name: ADDRESS\n              value: /csi/csi.sock\n\
    \          image: longhornio/csi-node-driver-registrar:v1.2.0-lh1\n          lifecycle:\n\
    \            preStop:\n              exec:\n                command:\n       \
    \           - /bin/sh\n                  - -c\n                  - rm -rf /registration/driver.harvesterhci.io-reg.sock\n\
    \                    /csi//*\n          name: node-driver-registrar\n        \
    \  securityContext:\n            privileged: true\n          volumeMounts:\n \
    \           - mountPath: /csi/\n              name: socket-dir\n            -\
    \ mountPath: /registration\n              name: registration-dir\n        - args:\n\
    \            - --nodeid=$(NODE_ID)\n            - --endpoint=$(CSI_ENDPOINT)\n\
    \            - --kubeconfig=/etc/csi/cloud-config\n          env:\n          \
    \  - name: NODE_ID\n              valueFrom:\n                fieldRef:\n    \
    \              apiVersion: v1\n                  fieldPath: spec.nodeName\n  \
    \          - name: CSI_ENDPOINT\n              value: unix:///csi/csi.sock\n \
    \         image: rancher/harvester-csi-driver:v0.1.6\n          imagePullPolicy:\
    \ Always\n          lifecycle:\n            preStop:\n              exec:\n  \
    \              command:\n                  - /bin/sh\n                  - -c\n\
    \                  - rm -f /csi//*\n          name: harvester-csi-plugin\n   \
    \       securityContext:\n            allowPrivilegeEscalation: true\n       \
    \     capabilities:\n              add:\n                - SYS_ADMIN\n       \
    \     privileged: true\n          volumeMounts:\n            - name: cloud-config\n\
    \              mountPath: \"/etc/csi\"\n              readOnly: true\n       \
    \     - mountPath: /var/lib/kubelet/plugins/kubernetes.io/csi\n              mountPropagation:\
    \ Bidirectional\n              name: kubernetes-csi-dir\n            - mountPath:\
    \ /csi/\n              name: socket-dir\n            - mountPath: /var/lib/kubelet/pods\n\
    \              mountPropagation: Bidirectional\n              name: pods-mount-dir\n\
    \            - mountPath: /dev\n              name: host-dev\n            - mountPath:\
    \ /sys\n              name: host-sys\n            - mountPath: /rootfs\n     \
    \         mountPropagation: Bidirectional\n              name: host\n        \
    \    - mountPath: /lib/modules\n              name: lib-modules\n            \
    \  readOnly: true\n      hostPID: true\n      serviceAccountName: harvester-csi\n\
    \      tolerations:\n        - effect: NoSchedule\n          key: node-role.kubernetes.io/control-plane\n\
    \          operator: Exists\n        - effect: NoSchedule\n          key: kubevirt.io/drain\n\
    \          operator: Exists\n      volumes:\n        - name: cloud-config\n  \
    \        secret:\n            secretName: cloud-config\n        - hostPath:\n\
    \            path: /var/lib/kubelet/plugins/kubernetes.io/csi\n            type:\
    \ DirectoryOrCreate\n          name: kubernetes-csi-dir\n        - hostPath:\n\
    \            path: /var/lib/kubelet/plugins_registry\n            type: Directory\n\
    \          name: registration-dir\n        - hostPath:\n            path: /var/lib/kubelet/harvester-plugins/driver.harvesterhci.io\n\
    \            type: DirectoryOrCreate\n          name: socket-dir\n        - hostPath:\n\
    \            path: /var/lib/kubelet/pods\n            type: DirectoryOrCreate\n\
    \          name: pods-mount-dir\n        - hostPath:\n            path: /dev\n\
    \          name: host-dev\n        - hostPath:\n            path: /sys\n     \
    \     name: host-sys\n        - hostPath:\n            path: /\n          name:\
    \ host\n        - hostPath:\n            path: /lib/modules\n          name: lib-modules\n\
    ---\napiVersion: v1\nkind: ServiceAccount\nmetadata:\n  name: harvester-csi\n\
    \  namespace: kube-system\n---\napiVersion: rbac.authorization.k8s.io/v1\nkind:\
    \ ClusterRoleBinding\nmetadata:\n  name: harvester-csi\nroleRef:\n  apiGroup:\
    \ rbac.authorization.k8s.io\n  kind: ClusterRole\n  name: cluster-admin\nsubjects:\n\
    \  - kind: ServiceAccount\n    name: harvester-csi\n    namespace: kube-system\n\
    ---\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: csi-controller\n\
    \  namespace: kube-system\nspec:\n  replicas: 1\n  selector:\n    matchLabels:\n\
    \      app: csi-controller\n  template:\n    metadata:\n      labels:\n      \
    \  app: csi-controller\n    spec:\n      containers:\n        - args:\n      \
    \      - --v=5\n            - --csi-address=$(ADDRESS)\n            - --csiTimeout=2m5s\n\
    \            - --leader-election\n            - --leader-election-namespace=$(POD_NAMESPACE)\n\
    \          env:\n            - name: ADDRESS\n              value: /csi/csi.sock\n\
    \            - name: POD_NAMESPACE\n              valueFrom:\n               \
    \ fieldRef:\n                  apiVersion: v1\n                  fieldPath: metadata.namespace\n\
    \          image: longhornio/csi-resizer:v0.5.1-lh1\n          name: csi-resizer\n\
    \          volumeMounts:\n            - mountPath: /csi/\n              name:\
    \ socket-dir\n        - args:\n            - --v=5\n            - --csi-address=$(ADDRESS)\n\
    \            - --timeout=2m5s\n            - --enable-leader-election\n      \
    \      - --leader-election-type=leases\n            - --leader-election-namespace=$(POD_NAMESPACE)\n\
    \          env:\n            - name: ADDRESS\n              value: /csi/csi.sock\n\
    \            - name: POD_NAMESPACE\n              valueFrom:\n               \
    \ fieldRef:\n                  apiVersion: v1\n                  fieldPath: metadata.namespace\n\
    \          image: longhornio/csi-provisioner:v1.6.0-lh1\n          name: csi-provisioner\n\
    \          volumeMounts:\n            - mountPath: /csi/\n              name:\
    \ socket-dir\n        - args:\n            - --v=5\n            - --csi-address=$(ADDRESS)\n\
    \            - --timeout=2m5s\n            - --leader-election\n            -\
    \ --leader-election-namespace=$(POD_NAMESPACE)\n          env:\n            -\
    \ name: ADDRESS\n              value: /csi/csi.sock\n            - name: POD_NAMESPACE\n\
    \              valueFrom:\n                fieldRef:\n                  apiVersion:\
    \ v1\n                  fieldPath: metadata.namespace\n          image: longhornio/csi-attacher:v2.2.1-lh1\n\
    \          name: csi-attacher\n          volumeMounts:\n            - mountPath:\
    \ /csi/\n              name: socket-dir\n      serviceAccountName: harvester-csi\n\
    \      tolerations:\n        - effect: NoSchedule\n          key: node-role.kubernetes.io/control-plane\n\
    \          operator: Exists\n        - effect: NoSchedule\n          key: kubevirt.io/drain\n\
    \          operator: Exists\n      volumes:\n        - hostPath:\n           \
    \ path: /var/lib/kubelet/harvester-plugins/driver.harvesterhci.io\n          \
    \  type: DirectoryOrCreate\n          name: socket-dir\n---\napiVersion: storage.k8s.io/v1\n\
    kind: CSIDriver\nmetadata:\n  name: driver.harvesterhci.io\nspec:\n  attachRequired:\
    \ true\n  fsGroupPolicy: ReadWriteOnceWithFSType\n  podInfoOnMount: true\n  volumeLifecycleModes:\n\
    \    - Persistent\n---\napiVersion: storage.k8s.io/v1\nkind: StorageClass\nmetadata:\n\
    \  name: harvester\nallowVolumeExpansion: true\nprovisioner: driver.harvesterhci.io\n\
    reclaimPolicy: Delete\nvolumeBindingMode: Immediate\n"
kind: ConfigMap
metadata:
  name: cloud-controller-manager-addon
  namespace: mgmtclusters
