kind: ConfigMap
apiVersion: v1
metadata:
  name: linkerd-config
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: controller
    linkerd.io/control-plane-ns: linkerd
  annotations:
    linkerd.io/created-by: linkerd/cli edge-20.10.1
data:
  global: '{"linkerdNamespace":"linkerd","cniEnabled":false,"version":"edge-20.10.1","identityContext":{"trustDomain":"cluster.local","trustAnchorsPem":"-----BEGIN
    CERTIFICATE-----\nMIIBrTCCAVSgAwIBAgIBATAKBggqhkjOPQQDAjApMScwJQYDVQQDEx5pZGVudGl0\neS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjAxMDA0MDI0ODQwWhcNMjExMDA0\nMDI0OTAwWjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9j\nYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASZmf4G3Gv0uLIghidK7hi8JQBy\n2SpE0SvMdkxcq5jWnkCcqaIla55PgsTrDE5kFQ0INslrJaKxzGnDE22uvI9xo20w\nazAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC\nMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0RBCIwIIIeaWRlbnRpdHkubGlua2VyZC5j\nbHVzdGVyLmxvY2FsMAoGCCqGSM49BAMCA0cAMEQCIEI5jVjmF2WPdtqvBI+uGqUh\n40GgD/83Y6iOCDULHpBqAiAOfBx0sOwo2rvaiG7DQfrj2n6UQrQIHcxmiTD+9Lb0\nKg==\n-----END
    CERTIFICATE-----\n","issuanceLifetime":"86400s","clockSkewAllowance":"20s","scheme":"linkerd.io/tls"},"autoInjectContext":null,"omitWebhookSideEffects":false,"clusterDomain":"cluster.local"}

    '
  proxy: '{"proxyImage":{"imageName":"ghcr.io/linkerd/proxy","pullPolicy":"IfNotPresent"},"proxyInitImage":{"imageName":"ghcr.io/linkerd/proxy-init","pullPolicy":"IfNotPresent"},"controlPort":{"port":4190},"ignoreInboundPorts":[],"ignoreOutboundPorts":[],"inboundPort":{"port":4143},"adminPort":{"port":4191},"outboundPort":{"port":4140},"resource":{"requestCpu":"","requestMemory":"","limitCpu":"","limitMemory":""},"proxyUid":"2102","logLevel":{"level":"warn,linkerd=info"},"disableExternalProfiles":true,"proxyVersion":"edge-20.10.1","proxyInitImageVersion":"v1.3.6","debugImage":{"imageName":"ghcr.io/linkerd/debug","pullPolicy":"IfNotPresent"},"debugImageVersion":"edge-20.10.1","destinationGetNetworks":"10.0.0.0/8,172.16.0.0/12,192.168.0.0/16","logFormat":"plain","outboundConnectTimeout":"","inboundConnectTimeout":""}

    '
  install: '{"cliVersion":"edge-20.10.1","flags":[]}

    '
  values: "controllerImage: ghcr.io/linkerd/controller\ncontrollerImageVersion: \"\
    \"\ncontrollerReplicas: 1\ncontrollerUID: 2103\ndashboard:\n  replicas: 1\ndebugContainer:\n\
    \  image:\n    name: ghcr.io/linkerd/debug\n    pullPolicy: IfNotPresent\n   \
    \ version: edge-20.10.1\ndestinationProxyResources: null\ndestinationResources:\
    \ null\ndisableHeartBeat: false\nenableH2Upgrade: true\nenablePodAntiAffinity:\
    \ false\nglobal:\n  cliVersion: linkerd/cli edge-20.10.1\n  clusterDomain: cluster.local\n\
    \  cniEnabled: false\n  controlPlaneTracing: false\n  controllerComponentLabel:\
    \ linkerd.io/control-plane-component\n  controllerImageVersion: \"\"\n  controllerLogLevel:\
    \ info\n  controllerNamespaceLabel: linkerd.io/control-plane-ns\n  createdByAnnotation:\
    \ linkerd.io/created-by\n  enableEndpointSlices: false\n  grafanaUrl: \"\"\n \
    \ highAvailability: false\n  identityTrustAnchorsPEM: |\n    -----BEGIN CERTIFICATE-----\n\
    \    MIIBrTCCAVSgAwIBAgIBATAKBggqhkjOPQQDAjApMScwJQYDVQQDEx5pZGVudGl0\n    eS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjAxMDA0MDI0ODQwWhcNMjExMDA0\n\
    \    MDI0OTAwWjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9j\n    YWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASZmf4G3Gv0uLIghidK7hi8JQBy\n\
    \    2SpE0SvMdkxcq5jWnkCcqaIla55PgsTrDE5kFQ0INslrJaKxzGnDE22uvI9xo20w\n    azAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC\n\
    \    MA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0RBCIwIIIeaWRlbnRpdHkubGlua2VyZC5j\n    bHVzdGVyLmxvY2FsMAoGCCqGSM49BAMCA0cAMEQCIEI5jVjmF2WPdtqvBI+uGqUh\n\
    \    40GgD/83Y6iOCDULHpBqAiAOfBx0sOwo2rvaiG7DQfrj2n6UQrQIHcxmiTD+9Lb0\n    Kg==\n\
    \    -----END CERTIFICATE-----\n  identityTrustDomain: cluster.local\n  imagePullPolicy:\
    \ IfNotPresent\n  imagePullSecrets: []\n  linkerdNamespaceLabel: linkerd.io/is-control-plane\n\
    \  linkerdVersion: edge-20.10.1\n  namespace: linkerd\n  prometheusUrl: \"\"\n\
    \  proxy:\n    capabilities: null\n    component: linkerd-controller\n    destinationGetNetworks:\
    \ 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16\n    disableIdentity: false\n    disableTap:\
    \ false\n    enableExternalProfiles: false\n    image:\n      name: ghcr.io/linkerd/proxy\n\
    \      pullPolicy: IfNotPresent\n      version: edge-20.10.1\n    inboundConnectTimeout:\
    \ 100ms\n    isGateway: false\n    logFormat: plain\n    logLevel: warn,linkerd=info\n\
    \    opaquePorts: \"\"\n    outboundConnectTimeout: 1000ms\n    ports:\n     \
    \ admin: 4191\n      control: 4190\n      inbound: 4143\n      outbound: 4140\n\
    \    requireIdentityOnInboundPorts: \"\"\n    resources:\n      cpu:\n       \
    \ limit: \"\"\n        request: \"\"\n      memory:\n        limit: \"\"\n   \
    \     request: \"\"\n    saMountPath: null\n    trace:\n      collectorSvcAccount:\
    \ default\n      collectorSvcAddr: \"\"\n    uid: 2102\n    waitBeforeExitSeconds:\
    \ 0\n    workloadKind: deployment\n  proxyContainerName: linkerd-proxy\n  proxyInit:\n\
    \    capabilities: null\n    closeWaitTimeoutSecs: 0\n    ignoreInboundPorts:\
    \ \"\"\n    ignoreOutboundPorts: \"\"\n    image:\n      name: ghcr.io/linkerd/proxy-init\n\
    \      pullPolicy: IfNotPresent\n      version: v1.3.6\n    resources:\n     \
    \ cpu:\n        limit: 100m\n        request: 10m\n      memory:\n        limit:\
    \ 50Mi\n        request: 10Mi\n    saMountPath: null\n    xtMountPath:\n     \
    \ mountPath: /run\n      name: linkerd-proxy-init-xtables-lock\n      readOnly:\
    \ false\n  proxyInjectAnnotation: linkerd.io/inject\n  proxyInjectDisabled: disabled\n\
    \  workloadNamespaceLabel: linkerd.io/workload-ns\ngrafana:\n  enabled: true\n\
    heartbeatResources: null\nheartbeatSchedule: '58 2 * * * '\nidentity:\n  issuer:\n\
    \    clockSkewAllowance: 20s\n    crtExpiry: \"2021-10-04T02:49:00Z\"\n    crtExpiryAnnotation:\
    \ linkerd.io/identity-issuer-expiry\n    issuanceLifetime: 24h0m0s\n    scheme:\
    \ linkerd.io/tls\n    tls:\n      crtPEM: |\n        -----BEGIN CERTIFICATE-----\n\
    \        MIIBrTCCAVSgAwIBAgIBATAKBggqhkjOPQQDAjApMScwJQYDVQQDEx5pZGVudGl0\n  \
    \      eS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjAxMDA0MDI0ODQwWhcNMjExMDA0\n    \
    \    MDI0OTAwWjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9j\n      \
    \  YWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASZmf4G3Gv0uLIghidK7hi8JQBy\n        2SpE0SvMdkxcq5jWnkCcqaIla55PgsTrDE5kFQ0INslrJaKxzGnDE22uvI9xo20w\n\
    \        azAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC\n  \
    \      MA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0RBCIwIIIeaWRlbnRpdHkubGlua2VyZC5j\n    \
    \    bHVzdGVyLmxvY2FsMAoGCCqGSM49BAMCA0cAMEQCIEI5jVjmF2WPdtqvBI+uGqUh\n      \
    \  40GgD/83Y6iOCDULHpBqAiAOfBx0sOwo2rvaiG7DQfrj2n6UQrQIHcxmiTD+9Lb0\n        Kg==\n\
    \        -----END CERTIFICATE-----\nidentityProxyResources: null\nidentityResources:\
    \ null\ninstallNamespace: true\nnodeSelector:\n  beta.kubernetes.io/os: linux\n\
    omitWebhookSideEffects: false\nprofileValidator:\n  caBundle: \"\"\n  crtPEM:\
    \ \"\"\n  externalSecret: false\nprometheus:\n  enabled: true\nproxyInjector:\n\
    \  caBundle: \"\"\n  crtPEM: \"\"\n  externalSecret: false\nproxyInjectorProxyResources:\
    \ null\nproxyInjectorResources: null\npublicAPIProxyResources: null\npublicAPIResources:\
    \ null\nrestrictDashboardPrivileges: false\nspValidatorProxyResources: null\n\
    spValidatorResources: null\nstage: \"\"\ntap:\n  caBundle: \"\"\n  crtPEM: \"\"\
    \n  externalSecret: false\ntapProxyResources: null\ntapResources: null\ntolerations:\
    \ null\ntracing:\n  enabled: false\nwebImage: ghcr.io/linkerd/web\nwebProxyResources:\
    \ null\nwebResources: null\nwebhookFailurePolicy: Ignore\n"
