kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-manual-democratic-csi-node
  labels:
    app.kubernetes.io/name: democratic-csi
    app.kubernetes.io/instance: csi-manual
    app.kubernetes.io/csi-role: node
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: democratic-csi
      app.kubernetes.io/instance: csi-manual
      app.kubernetes.io/csi-role: node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: democratic-csi
        app.kubernetes.io/instance: csi-manual
        app.kubernetes.io/csi-role: node
    spec:
      serviceAccount: csi-manual-democratic-csi-node-sa
      hostNetwork: true
      hostAliases: []
      hostIPC: true
      containers:
      - name: csi-driver
        image: docker.io/democraticcsi/democratic-csi:latest
        args:
        - --csi-version=1.5.0
        - --csi-name=org.democratic-csi.node-manual
        - --driver-config-file=/config/driver-config-file.yaml
        - --log-level=info
        - --csi-mode=node
        - --server-socket=/csi-data/csi.sock.internal
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        env:
        - name: CSI_NODE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NODE_EXTRA_CA_CERTS
          value: /tmp/certs/extra-ca-certs.crt
        terminationMessagePath: /tmp/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          failureThreshold: 3
          exec:
            command:
            - bin/liveness-probe
            - --csi-version=1.5.0
            - --csi-address=/csi-data/csi.sock.internal
          initialDelaySeconds: 10
          timeoutSeconds: 15
          periodSeconds: 60
        volumeMounts:
        - name: socket-dir
          mountPath: /csi-data
        - name: kubelet-dir
          mountPath: /var/lib/kubelet
          mountPropagation: Bidirectional
        - name: modules-dir
          mountPath: /lib/modules
          readOnly: true
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: udev-data
          mountPath: /run/udev
        - name: host-dir
          mountPath: /host
          mountPropagation: Bidirectional
        - mountPath: /sys
          name: sys-dir
        - name: dev-dir
          mountPath: /dev
        - name: config
          mountPath: /config
        - name: extra-ca-certs
          mountPath: /tmp/certs
      - name: csi-proxy
        image: docker.io/democraticcsi/csi-grpc-proxy:latest
        env:
        - name: BIND_TO
          value: unix:///csi-data/csi.sock
        - name: PROXY_TO
          value: unix:///csi-data/csi.sock.internal
        volumeMounts:
        - mountPath: /csi-data
          name: socket-dir
      - name: driver-registrar
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.11.1
        args:
        - --v=5
        - --csi-address=/csi-data/csi.sock
        - --kubelet-registration-path=/var/lib/kubelet/plugins/org.democratic-csi.node-manual/csi.sock
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        livenessProbe:
          exec:
            command:
            - /csi-node-driver-registrar
            - --kubelet-registration-path=/var/lib/kubelet/plugins/org.democratic-csi.node-manual/csi.sock
            - --mode=kubelet-registration-probe
        volumeMounts:
        - mountPath: /csi-data
          name: socket-dir
        - name: registration-dir
          mountPath: /registration
        - name: kubelet-dir
          mountPath: /var/lib/kubelet
      - name: cleanup
        image: docker.io/busybox:stable
        command:
        - /bin/sh
        - -c
        - --
        args:
        - while true; do sleep 2; done;
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - rm -rf /plugins/org.democratic-csi.node-manual /registration/org.democratic-csi.node-manual-reg.sock
        volumeMounts:
        - name: plugins-dir
          mountPath: /plugins
        - name: registration-dir
          mountPath: /registration
      volumes:
      - name: socket-dir
        hostPath:
          path: /var/lib/kubelet/plugins/org.democratic-csi.node-manual
          type: DirectoryOrCreate
      - name: plugins-dir
        hostPath:
          path: /var/lib/kubelet/plugins
          type: Directory
      - name: registration-dir
        hostPath:
          path: /var/lib/kubelet/plugins_registry
          type: Directory
      - name: kubelet-dir
        hostPath:
          path: /var/lib/kubelet
          type: Directory
      - name: dev-dir
        hostPath:
          path: /dev
          type: Directory
      - name: modules-dir
        hostPath:
          path: /lib/modules
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: udev-data
        hostPath:
          path: /run/udev
      - name: sys-dir
        hostPath:
          path: /sys
          type: Directory
      - name: host-dir
        hostPath:
          path: /
          type: Directory
      - name: config
        secret:
          secretName: csi-manual-democratic-csi-driver-config
      - name: extra-ca-certs
        configMap:
          name: csi-manual-democratic-csi
          items:
          - key: extra-ca-certs
            path: extra-ca-certs.crt
