apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: meu-rabbitmq
  namespace: default
  labels:
    app.kubernetes.io/instance: meu
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/version: 3.13.1
    helm.sh/chart: rabbitmq-14.0.2
spec:
  serviceName: meu-rabbitmq-headless
  podManagementPolicy: OrderedReady
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: meu
      app.kubernetes.io/name: rabbitmq
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: meu
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/version: 3.13.1
        helm.sh/chart: rabbitmq-14.0.2
      annotations:
        checksum/config: 31893304b9543385a6cfd387fc3f420ce10ecf11ceb47ddd55142920cebe87d1
        checksum/secret: 8f0c9325c878d16ae245eda8b02dd8491585334d493f057d1b4254a331576782
    spec:
      serviceAccountName: meu-rabbitmq
      affinity:
        podAffinity: null
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: meu
                  app.kubernetes.io/name: rabbitmq
              topologyKey: kubernetes.io/hostname
            weight: 1
        nodeAffinity: null
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      terminationGracePeriodSeconds: 120
      enableServiceLinks: true
      initContainers:
      - name: prepare-plugins-dir
        image: docker.io/bitnami/rabbitmq:3.13.1-debian-12-r0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 375m
            ephemeral-storage: 1024Mi
            memory: 384Mi
          requests:
            cpu: 250m
            ephemeral-storage: 50Mi
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
          seLinuxOptions: null
          seccompProfile:
            type: RuntimeDefault
        command:
        - /bin/bash
        args:
        - -ec
        - '#!/bin/bash


          . /opt/bitnami/scripts/liblog.sh


          info "Copying plugins dir to empty dir"

          # In order to not break the possibility of installing custom plugins, we
          need

          # to make the plugins directory writable, so we need to copy it to an empty
          dir volume

          cp -r --preserve=mode /opt/bitnami/rabbitmq/plugins/ /emptydir/app-plugins-dir

          '
        volumeMounts:
        - name: empty-dir
          mountPath: /emptydir
      containers:
      - name: rabbitmq
        image: docker.io/bitnami/rabbitmq:3.13.1-debian-12-r0
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
          seLinuxOptions: null
          seccompProfile:
            type: RuntimeDefault
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -ec
              - "if [[ -f /opt/bitnami/scripts/rabbitmq/nodeshutdown.sh ]]; then\n\
                \    /opt/bitnami/scripts/rabbitmq/nodeshutdown.sh -t \"120\" -d \"\
                false\"\nelse\n    rabbitmqctl stop_app\nfi\n"
        env:
        - name: BITNAMI_DEBUG
          value: 'false'
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RABBITMQ_FORCE_BOOT
          value: 'no'
        - name: RABBITMQ_NODE_NAME
          value: rabbit@$(MY_POD_NAME).meu-rabbitmq-headless.$(MY_POD_NAMESPACE).svc.cluster.local
        - name: RABBITMQ_MNESIA_DIR
          value: /opt/bitnami/rabbitmq/.rabbitmq/mnesia/$(RABBITMQ_NODE_NAME)
        - name: RABBITMQ_LDAP_ENABLE
          value: 'no'
        - name: RABBITMQ_LOGS
          value: '-'
        - name: RABBITMQ_ULIMIT_NOFILES
          value: '65536'
        - name: RABBITMQ_USE_LONGNAME
          value: 'true'
        - name: RABBITMQ_ERL_COOKIE
          valueFrom:
            secretKeyRef:
              name: meu-rabbitmq
              key: rabbitmq-erlang-cookie
        - name: RABBITMQ_LOAD_DEFINITIONS
          value: 'no'
        - name: RABBITMQ_DEFINITIONS_FILE
          value: /app/load_definition.json
        - name: RABBITMQ_SECURE_PASSWORD
          value: 'yes'
        - name: RABBITMQ_USERNAME
          value: user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: meu-rabbitmq
              key: rabbitmq-password
        - name: RABBITMQ_PLUGINS
          value: rabbitmq_management, rabbitmq_peer_discovery_k8s, rabbitmq_auth_backend_ldap
        envFrom: null
        ports:
        - name: amqp
          containerPort: 5672
        - name: dist
          containerPort: 25672
        - name: stats
          containerPort: 15672
        - name: epmd
          containerPort: 4369
        - name: metrics
          containerPort: 9419
        livenessProbe:
          failureThreshold: 6
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 20
          exec:
            command:
            - sh
            - -ec
            - curl -f --user user:$RABBITMQ_PASSWORD 127.0.0.1:15672/api/health/checks/virtual-hosts
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 20
          exec:
            command:
            - sh
            - -ec
            - curl -f --user user:$RABBITMQ_PASSWORD 127.0.0.1:15672/api/health/checks/local-alarms
        resources:
          limits:
            cpu: 375m
            ephemeral-storage: 1024Mi
            memory: 384Mi
          requests:
            cpu: 250m
            ephemeral-storage: 50Mi
            memory: 256Mi
        volumeMounts:
        - name: configuration
          mountPath: /bitnami/rabbitmq/conf
        - name: empty-dir
          mountPath: /tmp
          subPath: tmp-dir
        - name: empty-dir
          mountPath: /opt/bitnami/rabbitmq/etc/rabbitmq
          subPath: app-conf-dir
        - name: empty-dir
          mountPath: /opt/bitnami/rabbitmq/var/lib/rabbitmq
          subPath: app-tmp-dir
        - name: empty-dir
          mountPath: /opt/bitnami/rabbitmq/.rabbitmq/
          subPath: app-erlang-cookie
        - name: empty-dir
          mountPath: /opt/bitnami/rabbitmq/var/log/rabbitmq
          subPath: app-logs-dir
        - name: empty-dir
          mountPath: /opt/bitnami/rabbitmq/plugins
          subPath: app-plugins-dir
        - name: data
          mountPath: /opt/bitnami/rabbitmq/.rabbitmq/mnesia
      volumes:
      - name: empty-dir
        emptyDir: {}
      - name: configuration
        projected:
          sources:
          - secret:
              name: meu-rabbitmq-config
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
      labels:
        app.kubernetes.io/instance: meu
        app.kubernetes.io/name: rabbitmq
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
