apiVersion: v1
kind: ConfigMap
metadata:
  name: tezos-config
  namespace: testing
data:
  CHAIN_NAME: elric
  CHAIN_PARAMS: "{\n  \"bootstrap_peers\": [],\n  \"default_bootstrap_mutez\": \"\
    4000000000000\",\n  \"expected-proof-of-work\": 0,\n  \"network\": {\n      \"\
    activation_account_name\": \"tezos-baking-node-0\",\n      \"chain_name\": \"\
    elric\",\n      \"genesis\": {\n        \"block\": \"BKupwQVt7UoyuBDDpj17NEtT3M8a1hKDTuw1HahdANAMXznC5YC\"\
    ,\n        \"protocol\": \"Ps9mPmXaRzmzk35gbAYNCAw6UXdE2qoABTHbN2oEEc1qM7CwT9P\"\
    ,\n        \"timestamp\": \"2021-08-31T16:04:29.430078+00:00\"\n      }\n    },\n\
    \  \"protocol_activation\": {\n      \"deterministic_faucet_number_of_accounts\"\
    : 1000,\n      \"deterministic_faucet_seed\": \"oM0TxIV5gYNVd0T9kasdfnv352\",\n\
    \      \"protocol_hash\": \"PtJakart2xVj7pYXJBXrqHgd82rdkLey5ZeeGwDgPp9rhQUbSqY\"\
    ,\n      \"protocol_parameters\": {\n        \"baking_reward_bonus_per_slot\"\
    : \"4286\",\n        \"baking_reward_fixed_portion\": \"10000000\",\n        \"\
    blocks_per_commitment\": 4,\n        \"blocks_per_cycle\": 8,\n        \"blocks_per_stake_snapshot\"\
    : 4,\n        \"cache_sampler_state_cycles\": 8,\n        \"cache_script_size\"\
    : 100000000,\n        \"cache_stake_distribution_cycles\": 8,\n        \"consensus_committee_size\"\
    : 7000,\n        \"consensus_threshold\": 4667,\n        \"cost_per_byte\": \"\
    250\",\n        \"cycles_per_voting_period\": 1,\n        \"delay_increment_per_round\"\
    : \"5\",\n        \"double_baking_punishment\": \"640000000\",\n        \"endorsing_reward_per_slot\"\
    : \"2857\",\n        \"frozen_deposits_percentage\": 10,\n        \"hard_gas_limit_per_block\"\
    : \"5200000\",\n        \"hard_gas_limit_per_operation\": \"1040000\",\n     \
    \   \"hard_storage_limit_per_operation\": \"60000\",\n        \"liquidity_baking_subsidy\"\
    : \"2500000\",\n        \"liquidity_baking_sunset_level\": 10000000,\n       \
    \ \"liquidity_baking_toggle_ema_threshold\": 100000,\n        \"max_operations_time_to_live\"\
    : 120,\n        \"max_slashing_period\": 2,\n        \"min_proposal_quorum\":\
    \ 500,\n        \"minimal_block_delay\": \"5\",\n        \"minimal_participation_ratio\"\
    : {\n          \"denominator\": 3,\n          \"numerator\": 2\n        },\n \
    \       \"origination_size\": 257,\n        \"preserved_cycles\": 3,\n       \
    \ \"proof_of_work_threshold\": \"-1\",\n        \"quorum_max\": 7000,\n      \
    \  \"quorum_min\": 2000,\n        \"ratio_of_frozen_deposits_slashed_per_double_endorsement\"\
    : {\n          \"denominator\": 2,\n          \"numerator\": 1\n        },\n \
    \       \"sc_rollup_challenge_window_in_blocks\": 40,\n        \"sc_rollup_enable\"\
    : false,\n        \"sc_rollup_max_available_messages\": 1000000,\n        \"sc_rollup_origination_size\"\
    : 6314,\n        \"seed_nonce_revelation_tip\": \"125000\",\n        \"tokens_per_roll\"\
    : \"8000000000\",\n        \"tx_rollup_commitment_bond\": \"10000000000\",\n \
    \       \"tx_rollup_cost_per_byte_ema_factor\": 120,\n        \"tx_rollup_enable\"\
    : true,\n        \"tx_rollup_finality_period\": 10,\n        \"tx_rollup_hard_size_limit_per_inbox\"\
    : 500000,\n        \"tx_rollup_hard_size_limit_per_message\": 5000,\n        \"\
    tx_rollup_max_commitments_count\": 30,\n        \"tx_rollup_max_inboxes_count\"\
    : 15,\n        \"tx_rollup_max_messages_per_inbox\": 1010,\n        \"tx_rollup_max_ticket_payload_size\"\
    : 2048,\n        \"tx_rollup_max_withdrawals_per_batch\": 15,\n        \"tx_rollup_origination_size\"\
    : 4000,\n        \"tx_rollup_rejection_max_proof_size\": 30000,\n        \"tx_rollup_sunset_level\"\
    : 17280,\n        \"tx_rollup_withdraw_period\": 10\n      }\n    }\n}\n"
  FULL_SNAPSHOT_URL: ''
  FULL_TARBALL_URL: ''
  ROLLING_SNAPSHOT_URL: ''
  ROLLING_TARBALL_URL: ''
  ARCHIVE_TARBALL_URL: ''
  PREFER_TARBALLS: 'false'
  SNAPSHOT_METADATA_NETWORK_NAME: ''
  SNAPSHOT_SOURCE: ''
  OCTEZ_VERSION: tezos/tezos:v15-release
  NODE_GLOBALS: "{\n  \"config\": {},\n  \"env\": {}\n}\n"
  NODES: "{\n  \"as\": {\n    \"instances\": [\n      {}\n    ],\n    \"runs\": [\n\
    \      \"octez_node\"\n    ]\n  },\n  \"eu\": {\n    \"images\": {\n      \"octez\"\
    : \"tezos/tezos:v15-release\"\n    },\n    \"instances\": [\n      {\n       \
    \ \"bake_using_accounts\": [\n          \"tezos-baking-node-0\",\n          \"\
    a\",\n          \"b\",\n          \"c\",\n          \"d\"\n        ],\n      \
    \  \"config\": {\n          \"shell\": {\n            \"history_mode\": \"archive\"\
    \n          }\n        },\n        \"is_bootstrap_node\": true\n      },\n   \
    \   {\n        \"bake_using_account\": \"tacoinfraSigner\",\n        \"is_bootstrap_node\"\
    : true\n      },\n      {}\n    ],\n    \"labels\": {\n      \"rpc_node\": \"\
    true\"\n    },\n    \"runs\": [\n      \"octez_node\",\n      \"baker\",\n   \
    \   \"logger\",\n      \"metrics\"\n    ],\n    \"storage_size\": \"15Gi\"\n \
    \ },\n  \"us\": {\n    \"instances\": [\n      {},\n      {}\n    ],\n    \"runs\"\
    : [\n      \"octez_node\",\n      \"baker\"\n    ],\n    \"storage_size\": \"\
    15Gi\"\n  }\n}\n"
  OCTEZ_SIGNERS: "{\n  \"octez-signer-0\": {\n    \"accounts\": [\n      \"tezos-baking-node-0\"\
    \n    ],\n    \"name\": \"tezos-signer-0\"\n  }\n}\n"
  TACOINFRA_SIGNERS: "{\n  \"tacoinfra-signer\": {\n    \"accounts\": [\n      \"\
    tacoinfraSigner\"\n    ]\n  }\n}\n"
  OCTEZ_ROLLUP_NODES: '{}

    '
  OCTEZ_BAKERS: '{}

    '
