apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.rules: "groups:\n- name: devopscube demo alert\n  rules:\n  - alert:\
    \ High Pod Memory\n    expr: sum(container_memory_usage_bytes) > 1\n    for: 1m\n\
    \    labels:\n      severity: slack\n    annotations:\n      summary: High Memory\
    \ Usage"
  prometheus.yml: "global:\n  scrape_interval: 5s\n  evaluation_interval: 5s\nrule_files:\n\
    \  - /etc/prometheus/prometheus.rules\nalerting:\n  alertmanagers:\n  - scheme:\
    \ http\n    static_configs:\n    - targets:\n      - \"alertmanager.monitoring.svc:9093\"\
    \nscrape_configs:\n  - job_name: 'cockroachdb'\n    metrics_path: '/_status/vars'\n\
    \    scheme: 'https'\n    tls_config:\n      insecure_skip_verify: true\n    static_configs:\n\
    \      - targets: ['cockroach-db-public.default.svc.cluster.local:8080']\n   \
    \     labels:\n          cluster: 'database-cluster'\n  - job_name: \"rabbitmq\"\
    \n    static_configs:\n      - targets: [\"rabbitmq.default.svc.cluster.local:15692\"\
    ]\n  - job_name: 'node-exporter'\n    kubernetes_sd_configs:\n      - role: endpoints\n\
    \    relabel_configs:\n    - source_labels: [__meta_kubernetes_endpoints_name]\n\
    \      regex: 'node-exporter'\n      action: keep\n  - job_name: 'kubernetes-apiservers'\n\
    \    kubernetes_sd_configs:\n    - role: endpoints\n    scheme: https\n    tls_config:\n\
    \      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n    bearer_token_file:\
    \ /var/run/secrets/kubernetes.io/serviceaccount/token\n    relabel_configs:\n\
    \    - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name,\
    \ __meta_kubernetes_endpoint_port_name]\n      action: keep\n      regex: default;kubernetes;https\n\
    \  - job_name: 'kubernetes-nodes'\n    scheme: https\n    tls_config:\n      ca_file:\
    \ /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n    bearer_token_file:\
    \ /var/run/secrets/kubernetes.io/serviceaccount/token\n    kubernetes_sd_configs:\n\
    \    - role: node\n    relabel_configs:\n    - action: labelmap\n      regex:\
    \ __meta_kubernetes_node_label_(.+)\n    - target_label: __address__\n      replacement:\
    \ kubernetes.default.svc:443\n    - source_labels: [__meta_kubernetes_node_name]\n\
    \      regex: (.+)\n      target_label: __metrics_path__\n      replacement: /api/v1/nodes/${1}/proxy/metrics\n\
    \  - job_name: 'kubernetes-pods'\n    kubernetes_sd_configs:\n    - role: pod\n\
    \    relabel_configs:\n    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]\n\
    \      action: keep\n      regex: true\n    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]\n\
    \      action: replace\n      target_label: __metrics_path__\n      regex: (.+)\n\
    \    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]\n\
    \      action: replace\n      regex: ([^:]+)(?::\\d+)?;(\\d+)\n      replacement:\
    \ $1:$2\n      target_label: __address__\n    - action: labelmap\n      regex:\
    \ __meta_kubernetes_pod_label_(.+)\n    - source_labels: [__meta_kubernetes_namespace]\n\
    \      action: replace\n      target_label: kubernetes_namespace\n    - source_labels:\
    \ [__meta_kubernetes_pod_name]\n      action: replace\n      target_label: kubernetes_pod_name\n\
    \  - job_name: 'kube-state-metrics'\n    static_configs:\n      - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']\n\
    \  - job_name: 'kubernetes-cadvisor'\n    scheme: https\n    tls_config:\n   \
    \   ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n    bearer_token_file:\
    \ /var/run/secrets/kubernetes.io/serviceaccount/token\n    kubernetes_sd_configs:\n\
    \    - role: node\n    relabel_configs:\n    - action: labelmap\n      regex:\
    \ __meta_kubernetes_node_label_(.+)\n    - target_label: __address__\n      replacement:\
    \ kubernetes.default.svc:443\n    - source_labels: [__meta_kubernetes_node_name]\n\
    \      regex: (.+)\n      target_label: __metrics_path__\n      replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor\n\
    \  - job_name: 'kubernetes-service-endpoints'\n    kubernetes_sd_configs:\n  \
    \  - role: endpoints\n    relabel_configs:\n    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]\n\
    \      action: keep\n      regex: true\n    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]\n\
    \      action: replace\n      target_label: __scheme__\n      regex: (https?)\n\
    \    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]\n\
    \      action: replace\n      target_label: __metrics_path__\n      regex: (.+)\n\
    \    - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]\n\
    \      action: replace\n      target_label: __address__\n      regex: ([^:]+)(?::\\\
    d+)?;(\\d+)\n      replacement: $1:$2\n    - action: labelmap\n      regex: __meta_kubernetes_service_label_(.+)\n\
    \    - source_labels: [__meta_kubernetes_namespace]\n      action: replace\n \
    \     target_label: kubernetes_namespace\n    - source_labels: [__meta_kubernetes_service_name]\n\
    \      action: replace\n      target_label: kubernetes_name"
