kind: ConfigMap
metadata:
  name: prometheus
  namespace: monitoring
apiVersion: v1
data:
  prometheus.yaml: "global:\n  scrape_interval: 10s\n  scrape_timeout: 10s\n  evaluation_interval:\
    \ 10s\nrule_files:\n  - \"/etc/prometheus-rules/*.rules\"\nscrape_configs:   \
    \       \n  # kubernetes-apiservers metrics\n  - job_name: 'kubernetes-apiservers'\n\
    \    scheme: https\n    tls_config:\n      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n\
    \    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token\n\
    \    kubernetes_sd_configs:\n      - role: endpoints\n    relabel_configs:\n \
    \     - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name,\
    \ __meta_kubernetes_endpoint_port_name]\n        action: keep\n        regex:\
    \ default;kubernetes;https\n  \n  # node metrics\n  - job_name: 'kubernetes-nodes'\n\
    \    scheme: https\n    tls_config:\n      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n\
    \    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token\n\
    \    kubernetes_sd_configs:\n      - role: node\n    relabel_configs:\n      -\
    \ action: labelmap\n        regex: __meta_kubernetes_node_label_(.+)\n      -\
    \ replacement: kubernetes.default.svc:443\n        target_label: __address__\n\
    \      - source_labels: [__meta_kubernetes_node_name]\n        regex: (.+)\n \
    \       replacement: /api/v1/nodes/$1/proxy/metrics\n        target_label: __metrics_path__\n\
    \n  # node metric from cadvisor\n  - job_name: 'kubernetes-nodes-cadvisor'\n \
    \   scheme: https\n    tls_config:\n      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n\
    \    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token\n\
    \    kubernetes_sd_configs:\n      - role: node\n    relabel_configs:\n      -\
    \ action: labelmap\n        regex: __meta_kubernetes_node_label_(.+)\n      -\
    \ target_label: __address__\n        replacement: kubernetes.default.svc:443\n\
    \      - source_labels: [__meta_kubernetes_node_name]\n        regex: (.+)\n \
    \       target_label: __metrics_path__\n        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor\n\
    \  \n  # service endpoints metrics\n  - job_name: 'kubernetes-service-endpoints'\n\
    \    honor_labels: true\n    kubernetes_sd_configs:\n      - role: endpoints\n\
    \    relabel_configs:\n      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]\n\
    \        action: keep\n        regex: true\n      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]\n\
    \        action: replace\n        target_label: __scheme__\n        regex: (https?)\n\
    \      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]\n\
    \        action: replace\n        target_label: __metrics_path__\n        regex:\
    \ (.+)\n      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]\n\
    \        action: replace\n        target_label: __address__\n        regex: (.+)(?::\\\
    d+);(\\d+)\n        replacement: $1:$2\n      - action: labelmap\n        regex:\
    \ __meta_kubernetes_service_annotation_prometheus_io_param_(.+)\n        replacement:\
    \ __param_$1\n      - action: labelmap\n        regex: __meta_kubernetes_service_label_(.+)\n\
    \      - source_labels: [__meta_kubernetes_namespace]\n        action: replace\n\
    \        target_label: namespace\n      - source_labels: [__meta_kubernetes_service_name]\n\
    \        action: replace\n        target_label: service\n      - source_labels:\
    \ [__meta_kubernetes_pod_node_name]\n        action: replace\n        target_label:\
    \ node\n\n  # kubernetes services\n  - job_name: 'kubernetes-services'\n    honor_labels:\
    \ true\n    metrics_path: /probe\n    params:\n      module: [http_2xx]\n    kubernetes_sd_configs:\n\
    \      - role: service\n    relabel_configs:\n      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]\n\
    \        action: keep\n        regex: true\n      - source_labels: [__address__]\n\
    \        target_label: __param_target\n      - replacement: blackbox\n       \
    \ target_label: __address__\n      - source_labels: [__param_target]\n       \
    \ target_label: instance\n      - action: labelmap\n        regex: __meta_kubernetes_service_label_(.+)\n\
    \      - source_labels: [__meta_kubernetes_namespace]\n        target_label: namespace\n\
    \      - source_labels: [__meta_kubernetes_service_name]\n        target_label:\
    \ service\n\n  # kubernetes pods\n  - job_name: 'kubernetes-pods'\n    honor_labels:\
    \ true\n    kubernetes_sd_configs:\n      - role: pod\n    relabel_configs:\n\
    \      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]\n\
    \        action: keep\n        regex: true\n      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]\n\
    \        action: replace\n        regex: (https?)\n        target_label: __scheme__\n\
    \      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]\n\
    \        action: replace\n        regex: (.+)\n        target_label: __metrics_path__\n\
    \      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port,\
    \ __meta_kubernetes_pod_ip]\n        action: replace\n        regex: (\\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})\n\
    \        replacement: '[$2]:$1'\n        target_label: __address__\n      - source_labels:\
    \ [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_ip]\n\
    \        action: replace\n        regex: (\\d+);((([0-9]+?)(\\.|$)){4})\n    \
    \    replacement: $2:$1\n        target_label: __address__\n      - action: labelmap\n\
    \        regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)\n  \
    \      replacement: __param_$1\n      - action: labelmap\n        regex: __meta_kubernetes_pod_label_(.+)\n\
    \      - source_labels: [__meta_kubernetes_namespace]\n        action: replace\n\
    \        target_label: namespace\n      - source_labels: [__meta_kubernetes_pod_name]\n\
    \        action: replace\n        target_label: pod\n      - source_labels: [__meta_kubernetes_pod_phase]\n\
    \        action: drop\n        regex: Pending|Succeeded|Failed|Completed\n   \
    \   - source_labels: [__meta_kubernetes_pod_node_name]\n        action: replace\n\
    \        target_label: node\n\n  # kepler\n  - job_name: 'kepler'\n    kubernetes_sd_configs:\n\
    \    - role: node\n    relabel_configs:\n    - source_labels: [__address__]\n\
    \      regex: ^(.*):\\d+$\n      target_label: __address__\n      replacement:\
    \ $1:9102\n  \n  # powertop-exporter\n  - job_name: 'powertop-exporter'\n    kubernetes_sd_configs:\n\
    \    - role: node\n    relabel_configs:\n    - source_labels: [__address__]\n\
    \      regex: ^(.*):\\d+$\n      target_label: __address__\n      replacement:\
    \ $1:8887\n\n  # nmbn-exporter\n  - job_name: 'nmbn-exporter'\n    kubernetes_sd_configs:\n\
    \    - role: node\n    relabel_configs:\n    - source_labels: [__address__]\n\
    \      regex: ^(.*):\\d+$\n      target_label: __address__\n      replacement:\
    \ $1:9279\n    - target_label: __scheme__\n      replacement: http\n    # Host\
    \ name\n    - source_labels: [__meta_kubernetes_node_name]\n      target_label:\
    \ instance\nstorage:\n  exemplars:\n    max_exemplars: 100000\n"
