apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: main
  namespace: part5-stackgres-operator
webhooks:
- name: sgcluster.mutating-webhook.stackgres.io
  sideEffects: None
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - stackgres.io
    apiVersions:
    - '*'
    resources:
    - sgclusters
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: part5-stackgres-operator
      name: main
      path: /stackgres/mutation/sgcluster
    caBundle: Cg==
  admissionReviewVersions:
  - v1
- name: sgpgconfig.mutating-webhook.stackgres.io
  sideEffects: None
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - stackgres.io
    apiVersions:
    - '*'
    resources:
    - sgpgconfigs
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: part5-stackgres-operator
      name: main
      path: /stackgres/mutation/sgpgconfig
    caBundle: Cg==
  admissionReviewVersions:
  - v1
- name: sgpoolconfig.mutating-webhook.stackgres.io
  sideEffects: None
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - stackgres.io
    apiVersions:
    - '*'
    resources:
    - sgpoolconfigs
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: part5-stackgres-operator
      name: main
      path: /stackgres/mutation/sgpoolconfig
    caBundle: Cg==
  admissionReviewVersions:
  - v1
- name: sginstanceprofile.mutating-webhook.stackgres.io
  sideEffects: None
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - stackgres.io
    apiVersions:
    - '*'
    resources:
    - sginstanceprofiles
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: part5-stackgres-operator
      name: main
      path: /stackgres/mutation/sginstanceprofile
    caBundle: Cg==
  admissionReviewVersions:
  - v1
- name: sgbackupconfig.mutating-webhook.stackgres.io
  sideEffects: None
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - stackgres.io
    apiVersions:
    - '*'
    resources:
    - sgbackupconfigs
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: part5-stackgres-operator
      name: main
      path: /stackgres/mutation/sgbackupconfig
    caBundle: Cg==
  admissionReviewVersions:
  - v1
- name: sgbackup.mutating-webhook.stackgres.io
  sideEffects: None
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - stackgres.io
    apiVersions:
    - '*'
    resources:
    - sgbackups
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: part5-stackgres-operator
      name: main
      path: /stackgres/mutation/sgbackup
    caBundle: Cg==
  admissionReviewVersions:
  - v1
- name: sgdistributedlogs.mutating-webhook.stackgres.io
  sideEffects: None
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - stackgres.io
    apiVersions:
    - '*'
    resources:
    - sgdistributedlogs
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: part5-stackgres-operator
      name: main
      path: /stackgres/mutation/sgdistributedlogs
    caBundle: Cg==
  admissionReviewVersions:
  - v1
- name: sgdbops.mutating-webhook.stackgres.io
  sideEffects: None
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - stackgres.io
    apiVersions:
    - '*'
    resources:
    - sgdbops
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: part5-stackgres-operator
      name: main
      path: /stackgres/mutation/sgdbops
    caBundle: Cg==
  admissionReviewVersions:
  - v1
- name: sgobjectstorage.mutating-webhook.stackgres.io
  sideEffects: None
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - stackgres.io
    apiVersions:
    - '*'
    resources:
    - sgobjectstorages
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: part5-stackgres-operator
      name: main
      path: /stackgres/mutation/sgobjectstorage
    caBundle: Cg==
  admissionReviewVersions:
  - v1
- name: sgscripts.mutating-webhook.stackgres.io
  sideEffects: None
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - stackgres.io
    apiVersions:
    - '*'
    resources:
    - sgscripts
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: part5-stackgres-operator
      name: main
      path: /stackgres/mutation/sgscript
    caBundle: Cg==
  admissionReviewVersions:
  - v1
- name: sgshardedclusters.mutating-webhook.stackgres.io
  sideEffects: None
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - stackgres.io
    apiVersions:
    - '*'
    resources:
    - sgshardedclusters
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: part5-stackgres-operator
      name: main
      path: /stackgres/mutation/sgshardedcluster
    caBundle: Cg==
  admissionReviewVersions:
  - v1
- name: sgshardedbackups.mutating-webhook.stackgres.io
  sideEffects: None
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - stackgres.io
    apiVersions:
    - '*'
    resources:
    - sgshardedbackups
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: part5-stackgres-operator
      name: main
      path: /stackgres/mutation/sgshardedbackup
    caBundle: Cg==
  admissionReviewVersions:
  - v1
- name: sgshardeddbops.mutating-webhook.stackgres.io
  sideEffects: None
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - stackgres.io
    apiVersions:
    - '*'
    resources:
    - sgshardeddbops
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: part5-stackgres-operator
      name: main
      path: /stackgres/mutation/sgshardeddbops
    caBundle: Cg==
  admissionReviewVersions:
  - v1
- name: sgstreams.mutating-webhook.stackgres.io
  sideEffects: None
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - stackgres.io
    apiVersions:
    - '*'
    resources:
    - sgstreams
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: part5-stackgres-operator
      name: main
      path: /stackgres/mutation/sgstreams
    caBundle: Cg==
  admissionReviewVersions:
  - v1
