apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: istio-system
  labels:
    app: prometheus
    chart: prometheus-0.1.0
    release: RELEASE-NAME
    heritage: Tiller
data:
  prometheus.yml: "global:\n  scrape_interval: 15s\nscrape_configs:\n\n- job_name:\
    \ 'istio-mesh'\n  # Override the global default and scrape targets from this job\
    \ every 5 seconds.\n  scrape_interval: 5s\n\n  kubernetes_sd_configs:\n  - role:\
    \ endpoints\n    namespaces:\n      names:\n      - istio-system\n\n  relabel_configs:\n\
    \  - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]\n\
    \    action: keep\n    regex: istio-telemetry;prometheus\n\n- job_name: 'envoy'\n\
    \  # Override the global default and scrape targets from this job every 5 seconds.\n\
    \  scrape_interval: 5s\n  # metrics_path defaults to '/metrics'\n  # scheme defaults\
    \ to 'http'.\n\n  kubernetes_sd_configs:\n  - role: endpoints\n    namespaces:\n\
    \      names:\n      - istio-system\n\n  relabel_configs:\n  - source_labels:\
    \ [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]\n   \
    \ action: keep\n    regex: istio-statsd-prom-bridge;statsd-prom\n\n- job_name:\
    \ 'istio-policy'\n  # Override the global default and scrape targets from this\
    \ job every 5 seconds.\n  scrape_interval: 5s\n  # metrics_path defaults to '/metrics'\n\
    \  # scheme defaults to 'http'.\n\n  kubernetes_sd_configs:\n  - role: endpoints\n\
    \    namespaces:\n      names:\n      - istio-system\n\n\n  relabel_configs:\n\
    \  - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]\n\
    \    action: keep\n    regex: istio-policy;http-monitoring\n\n- job_name: 'istio-telemetry'\n\
    \  # Override the global default and scrape targets from this job every 5 seconds.\n\
    \  scrape_interval: 5s\n  # metrics_path defaults to '/metrics'\n  # scheme defaults\
    \ to 'http'.\n\n  kubernetes_sd_configs:\n  - role: endpoints\n    namespaces:\n\
    \      names:\n      - istio-system\n\n  relabel_configs:\n  - source_labels:\
    \ [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]\n   \
    \ action: keep\n    regex: istio-telemetry;http-monitoring\n\n- job_name: 'pilot'\n\
    \  # Override the global default and scrape targets from this job every 5 seconds.\n\
    \  scrape_interval: 5s\n  # metrics_path defaults to '/metrics'\n  # scheme defaults\
    \ to 'http'.\n\n  kubernetes_sd_configs:\n  - role: endpoints\n    namespaces:\n\
    \      names:\n      - istio-system\n\n  relabel_configs:\n  - source_labels:\
    \ [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]\n   \
    \ action: keep\n    regex: istio-pilot;http-monitoring\n\n- job_name: 'galley'\n\
    \  # Override the global default and scrape targets from this job every 5 seconds.\n\
    \  scrape_interval: 5s\n  # metrics_path defaults to '/metrics'\n  # scheme defaults\
    \ to 'http'.\n\n  kubernetes_sd_configs:\n  - role: endpoints\n    namespaces:\n\
    \      names:\n      - istio-system\n\n  relabel_configs:\n  - source_labels:\
    \ [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]\n   \
    \ action: keep\n    regex: istio-galley;http-monitoring\n\n# scrape config for\
    \ API servers\n- job_name: 'kubernetes-apiservers'\n  kubernetes_sd_configs:\n\
    \  - role: endpoints\n    namespaces:\n      names:\n      - default\n  scheme:\
    \ https\n  tls_config:\n    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n\
    \  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token\n  relabel_configs:\n\
    \  - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]\n\
    \    action: keep\n    regex: kubernetes;https\n\n# scrape config for nodes (kubelet)\n\
    - job_name: 'kubernetes-nodes'\n  scheme: https\n  tls_config:\n    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n\
    \  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token\n  kubernetes_sd_configs:\n\
    \  - role: node\n  relabel_configs:\n  - action: labelmap\n    regex: __meta_kubernetes_node_label_(.+)\n\
    \  - target_label: __address__\n    replacement: kubernetes.default.svc:443\n\
    \  - source_labels: [__meta_kubernetes_node_name]\n    regex: (.+)\n    target_label:\
    \ __metrics_path__\n    replacement: /api/v1/nodes/${1}/proxy/metrics\n\n# Scrape\
    \ config for Kubelet cAdvisor.\n#\n# This is required for Kubernetes 1.7.3 and\
    \ later, where cAdvisor metrics\n# (those whose names begin with 'container_')\
    \ have been removed from the\n# Kubelet metrics endpoint.  This job scrapes the\
    \ cAdvisor endpoint to\n# retrieve those metrics.\n#\n# In Kubernetes 1.7.0-1.7.2,\
    \ these metrics are only exposed on the cAdvisor\n# HTTP endpoint; use \"replacement:\
    \ /api/v1/nodes/${1}:4194/proxy/metrics\"\n# in that case (and ensure cAdvisor's\
    \ HTTP server hasn't been disabled with\n# the --cadvisor-port=0 Kubelet flag).\n\
    #\n# This job is not necessary and should be removed in Kubernetes 1.6 and\n#\
    \ earlier versions, or it will cause the metrics to be scraped twice.\n- job_name:\
    \ 'kubernetes-cadvisor'\n  scheme: https\n  tls_config:\n    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n\
    \  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token\n  kubernetes_sd_configs:\n\
    \  - role: node\n  relabel_configs:\n  - action: labelmap\n    regex: __meta_kubernetes_node_label_(.+)\n\
    \  - target_label: __address__\n    replacement: kubernetes.default.svc:443\n\
    \  - source_labels: [__meta_kubernetes_node_name]\n    regex: (.+)\n    target_label:\
    \ __metrics_path__\n    replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor\n\
    \n# scrape config for service endpoints.\n- job_name: 'kubernetes-service-endpoints'\n\
    \  kubernetes_sd_configs:\n  - role: endpoints\n  relabel_configs:\n  - source_labels:\
    \ [__meta_kubernetes_service_annotation_prometheus_io_scrape]\n    action: keep\n\
    \    regex: true\n  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]\n\
    \    action: replace\n    target_label: __scheme__\n    regex: (https?)\n  - source_labels:\
    \ [__meta_kubernetes_service_annotation_prometheus_io_path]\n    action: replace\n\
    \    target_label: __metrics_path__\n    regex: (.+)\n  - source_labels: [__address__,\
    \ __meta_kubernetes_service_annotation_prometheus_io_port]\n    action: replace\n\
    \    target_label: __address__\n    regex: ([^:]+)(?::\\d+)?;(\\d+)\n    replacement:\
    \ $1:$2\n  - action: labelmap\n    regex: __meta_kubernetes_service_label_(.+)\n\
    \  - source_labels: [__meta_kubernetes_namespace]\n    action: replace\n    target_label:\
    \ kubernetes_namespace\n  - source_labels: [__meta_kubernetes_service_name]\n\
    \    action: replace\n    target_label: kubernetes_name\n\n# Example scrape config\
    \ for pods\n- job_name: 'kubernetes-pods'\n  kubernetes_sd_configs:\n  - role:\
    \ pod\n\n  relabel_configs:\n  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]\n\
    \    action: keep\n    regex: true\n  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]\n\
    \    action: replace\n    target_label: __metrics_path__\n    regex: (.+)\n  -\
    \ source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]\n\
    \    action: replace\n    regex: ([^:]+)(?::\\d+)?;(\\d+)\n    replacement: $1:$2\n\
    \    target_label: __address__\n  - action: labelmap\n    regex: __meta_kubernetes_pod_label_(.+)\n\
    \  - source_labels: [__meta_kubernetes_namespace]\n    action: replace\n    target_label:\
    \ namespace\n  - source_labels: [__meta_kubernetes_pod_name]\n    action: replace\n\
    \    target_label: pod_name"
