apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: disallowdefaultns
spec:
  crd:
    spec:
      names:
        kind: DisallowDefaultNamespace
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package disallowdefaultns

        deny[{"msg": msg}] {
          input.review.object.metadata.namespace == "default"
          msg := "Usage of the 'default' namespace is not allowed."
        }