apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AllowedCapabilities
metadata:
  name: restrict-capabilities
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedCapabilities:
      - "NET_BIND_SERVICE"