apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: allowedcapabilities
spec:
  crd:
    spec:
      names:
        kind: AllowedCapabilities
      validation:
        openAPIV3Schema:
          type: object
          properties:
            allowedCapabilities:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package allowedcapabilities

        deny[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          cap := container.securityContext.capabilities.add[_]
          not cap in input.parameters.allowedCapabilities
          msg := sprintf("Capability %s is not allowed in container '%s'", [cap, container.name])
        }