apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      initContainers:
      - name: install-envsubst
        image: tbalza/envsubst:latest
        command:
        - /bin/sh
        - -c
        args:
        - cp /usr/local/bin/envsubst /tmp/envsubst
        volumeMounts:
        - name: custom-bin
          mountPath: /custom-bin
      containers:
      - name: argocd-repo-server
        image: quay.io/argoproj/argocd:v2.7.11
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        env:
        - name: PATH
          value: /tmp:${PATH}
        volumeMounts:
        - mountPath: /tmp
          name: custom-bin
          subPath: envsubst
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: kustomize-build-with-helm-and-envsubst.yaml
          name: argocd-cmp-kustomize-build-with-helm-and-envsubst
        - mountPath: /tmp
          name: cmp-tmp
      volumes:
      - name: custom-bin
        emptyDir: {}
      - name: var-files
        emptyDir: {}
      - name: plugins
        emptyDir: {}
      - name: argocd-cmp-kustomize-build-with-helm-and-envsubst
        configMap:
          name: kustomize-build-with-helm-and-envsubst
      - name: cmp-tmp
        emptyDir: {}
